// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: google/cloud/aiplatform/v1/pipeline_failure_policy.proto

package aiplatformpb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents the failure policy of a pipeline. Currently, the default of a
// pipeline is that the pipeline will continue to run until no more tasks can be
// executed, also known as PIPELINE_FAILURE_POLICY_FAIL_SLOW. However, if a
// pipeline is set to PIPELINE_FAILURE_POLICY_FAIL_FAST, it will stop scheduling
// any new tasks when a task has failed. Any scheduled tasks will continue to
// completion.
type PipelineFailurePolicy int32

const (
	// Default value, and follows fail slow behavior.
	PipelineFailurePolicy_PIPELINE_FAILURE_POLICY_UNSPECIFIED PipelineFailurePolicy = 0
	// Indicates that the pipeline should continue to run until all possible
	// tasks have been scheduled and completed.
	PipelineFailurePolicy_PIPELINE_FAILURE_POLICY_FAIL_SLOW PipelineFailurePolicy = 1
	// Indicates that the pipeline should stop scheduling new tasks after a task
	// has failed.
	PipelineFailurePolicy_PIPELINE_FAILURE_POLICY_FAIL_FAST PipelineFailurePolicy = 2
)

// Enum value maps for PipelineFailurePolicy.
var (
	PipelineFailurePolicy_name = map[int32]string{
		0: "PIPELINE_FAILURE_POLICY_UNSPECIFIED",
		1: "PIPELINE_FAILURE_POLICY_FAIL_SLOW",
		2: "PIPELINE_FAILURE_POLICY_FAIL_FAST",
	}
	PipelineFailurePolicy_value = map[string]int32{
		"PIPELINE_FAILURE_POLICY_UNSPECIFIED": 0,
		"PIPELINE_FAILURE_POLICY_FAIL_SLOW":   1,
		"PIPELINE_FAILURE_POLICY_FAIL_FAST":   2,
	}
)

func (x PipelineFailurePolicy) Enum() *PipelineFailurePolicy {
	p := new(PipelineFailurePolicy)
	*p = x
	return p
}

func (x PipelineFailurePolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PipelineFailurePolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_google_cloud_aiplatform_v1_pipeline_failure_policy_proto_enumTypes[0].Descriptor()
}

func (PipelineFailurePolicy) Type() protoreflect.EnumType {
	return &file_google_cloud_aiplatform_v1_pipeline_failure_policy_proto_enumTypes[0]
}

func (x PipelineFailurePolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PipelineFailurePolicy.Descriptor instead.
func (PipelineFailurePolicy) EnumDescriptor() ([]byte, []int) {
	return file_google_cloud_aiplatform_v1_pipeline_failure_policy_proto_rawDescGZIP(), []int{0}
}

var File_google_cloud_aiplatform_v1_pipeline_failure_policy_proto protoreflect.FileDescriptor

const file_google_cloud_aiplatform_v1_pipeline_failure_policy_proto_rawDesc = "" +
	"\n" +
	"8google/cloud/aiplatform/v1/pipeline_failure_policy.proto\x12\x1agoogle.cloud.aiplatform.v1*\x8e\x01\n" +
	"\x15PipelineFailurePolicy\x12'\n" +
	"#PIPELINE_FAILURE_POLICY_UNSPECIFIED\x10\x00\x12%\n" +
	"!PIPELINE_FAILURE_POLICY_FAIL_SLOW\x10\x01\x12%\n" +
	"!PIPELINE_FAILURE_POLICY_FAIL_FAST\x10\x02B\xd8\x01\n" +
	"\x1ecom.google.cloud.aiplatform.v1B\x1aPipelineFailurePolicyProtoP\x01Z>cloud.google.com/go/aiplatform/apiv1/aiplatformpb;aiplatformpb\xaa\x02\x1aGoogle.Cloud.AIPlatform.V1\xca\x02\x1aGoogle\\Cloud\\AIPlatform\\V1\xea\x02\x1dGoogle::Cloud::AIPlatform::V1b\x06proto3"

var (
	file_google_cloud_aiplatform_v1_pipeline_failure_policy_proto_rawDescOnce sync.Once
	file_google_cloud_aiplatform_v1_pipeline_failure_policy_proto_rawDescData []byte
)

func file_google_cloud_aiplatform_v1_pipeline_failure_policy_proto_rawDescGZIP() []byte {
	file_google_cloud_aiplatform_v1_pipeline_failure_policy_proto_rawDescOnce.Do(func() {
		file_google_cloud_aiplatform_v1_pipeline_failure_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_cloud_aiplatform_v1_pipeline_failure_policy_proto_rawDesc), len(file_google_cloud_aiplatform_v1_pipeline_failure_policy_proto_rawDesc)))
	})
	return file_google_cloud_aiplatform_v1_pipeline_failure_policy_proto_rawDescData
}

var file_google_cloud_aiplatform_v1_pipeline_failure_policy_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_google_cloud_aiplatform_v1_pipeline_failure_policy_proto_goTypes = []any{
	(PipelineFailurePolicy)(0), // 0: google.cloud.aiplatform.v1.PipelineFailurePolicy
}
var file_google_cloud_aiplatform_v1_pipeline_failure_policy_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_google_cloud_aiplatform_v1_pipeline_failure_policy_proto_init() }
func file_google_cloud_aiplatform_v1_pipeline_failure_policy_proto_init() {
	if File_google_cloud_aiplatform_v1_pipeline_failure_policy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_cloud_aiplatform_v1_pipeline_failure_policy_proto_rawDesc), len(file_google_cloud_aiplatform_v1_pipeline_failure_policy_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_cloud_aiplatform_v1_pipeline_failure_policy_proto_goTypes,
		DependencyIndexes: file_google_cloud_aiplatform_v1_pipeline_failure_policy_proto_depIdxs,
		EnumInfos:         file_google_cloud_aiplatform_v1_pipeline_failure_policy_proto_enumTypes,
	}.Build()
	File_google_cloud_aiplatform_v1_pipeline_failure_policy_proto = out.File
	file_google_cloud_aiplatform_v1_pipeline_failure_policy_proto_goTypes = nil
	file_google_cloud_aiplatform_v1_pipeline_failure_policy_proto_depIdxs = nil
}
