// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.7
// source: google/cloud/oracledatabase/v1/autonomous_database_character_set.proto

package oracledatabasepb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The type of character set an Autonomous Database can have.
type AutonomousDatabaseCharacterSet_CharacterSetType int32

const (
	// Character set type is not specified.
	AutonomousDatabaseCharacterSet_CHARACTER_SET_TYPE_UNSPECIFIED AutonomousDatabaseCharacterSet_CharacterSetType = 0
	// Character set type is set to database.
	AutonomousDatabaseCharacterSet_DATABASE AutonomousDatabaseCharacterSet_CharacterSetType = 1
	// Character set type is set to national.
	AutonomousDatabaseCharacterSet_NATIONAL AutonomousDatabaseCharacterSet_CharacterSetType = 2
)

// Enum value maps for AutonomousDatabaseCharacterSet_CharacterSetType.
var (
	AutonomousDatabaseCharacterSet_CharacterSetType_name = map[int32]string{
		0: "CHARACTER_SET_TYPE_UNSPECIFIED",
		1: "DATABASE",
		2: "NATIONAL",
	}
	AutonomousDatabaseCharacterSet_CharacterSetType_value = map[string]int32{
		"CHARACTER_SET_TYPE_UNSPECIFIED": 0,
		"DATABASE":                       1,
		"NATIONAL":                       2,
	}
)

func (x AutonomousDatabaseCharacterSet_CharacterSetType) Enum() *AutonomousDatabaseCharacterSet_CharacterSetType {
	p := new(AutonomousDatabaseCharacterSet_CharacterSetType)
	*p = x
	return p
}

func (x AutonomousDatabaseCharacterSet_CharacterSetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AutonomousDatabaseCharacterSet_CharacterSetType) Descriptor() protoreflect.EnumDescriptor {
	return file_google_cloud_oracledatabase_v1_autonomous_database_character_set_proto_enumTypes[0].Descriptor()
}

func (AutonomousDatabaseCharacterSet_CharacterSetType) Type() protoreflect.EnumType {
	return &file_google_cloud_oracledatabase_v1_autonomous_database_character_set_proto_enumTypes[0]
}

func (x AutonomousDatabaseCharacterSet_CharacterSetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AutonomousDatabaseCharacterSet_CharacterSetType.Descriptor instead.
func (AutonomousDatabaseCharacterSet_CharacterSetType) EnumDescriptor() ([]byte, []int) {
	return file_google_cloud_oracledatabase_v1_autonomous_database_character_set_proto_rawDescGZIP(), []int{0, 0}
}

// Details of the Autonomous Database character set resource.
// https://docs.oracle.com/en-us/iaas/api/#/en/database/20160918/AutonomousDatabaseCharacterSets/
type AutonomousDatabaseCharacterSet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier. The name of the Autonomous Database Character Set resource in
	// the following format:
	// projects/{project}/locations/{region}/autonomousDatabaseCharacterSets/{autonomous_database_character_set}
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Output only. The character set type for the Autonomous Database.
	CharacterSetType AutonomousDatabaseCharacterSet_CharacterSetType `protobuf:"varint,2,opt,name=character_set_type,json=characterSetType,proto3,enum=google.cloud.oracledatabase.v1.AutonomousDatabaseCharacterSet_CharacterSetType" json:"character_set_type,omitempty"`
	// Output only. The character set name for the Autonomous Database which is
	// the ID in the resource name.
	CharacterSet  string `protobuf:"bytes,3,opt,name=character_set,json=characterSet,proto3" json:"character_set,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutonomousDatabaseCharacterSet) Reset() {
	*x = AutonomousDatabaseCharacterSet{}
	mi := &file_google_cloud_oracledatabase_v1_autonomous_database_character_set_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutonomousDatabaseCharacterSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutonomousDatabaseCharacterSet) ProtoMessage() {}

func (x *AutonomousDatabaseCharacterSet) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_oracledatabase_v1_autonomous_database_character_set_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutonomousDatabaseCharacterSet.ProtoReflect.Descriptor instead.
func (*AutonomousDatabaseCharacterSet) Descriptor() ([]byte, []int) {
	return file_google_cloud_oracledatabase_v1_autonomous_database_character_set_proto_rawDescGZIP(), []int{0}
}

func (x *AutonomousDatabaseCharacterSet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AutonomousDatabaseCharacterSet) GetCharacterSetType() AutonomousDatabaseCharacterSet_CharacterSetType {
	if x != nil {
		return x.CharacterSetType
	}
	return AutonomousDatabaseCharacterSet_CHARACTER_SET_TYPE_UNSPECIFIED
}

func (x *AutonomousDatabaseCharacterSet) GetCharacterSet() string {
	if x != nil {
		return x.CharacterSet
	}
	return ""
}

var File_google_cloud_oracledatabase_v1_autonomous_database_character_set_proto protoreflect.FileDescriptor

const file_google_cloud_oracledatabase_v1_autonomous_database_character_set_proto_rawDesc = "" +
	"\n" +
	"Fgoogle/cloud/oracledatabase/v1/autonomous_database_character_set.proto\x12\x1egoogle.cloud.oracledatabase.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\"\xaf\x04\n" +
	"\x1eAutonomousDatabaseCharacterSet\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\bR\x04name\x12\x82\x01\n" +
	"\x12character_set_type\x18\x02 \x01(\x0e2O.google.cloud.oracledatabase.v1.AutonomousDatabaseCharacterSet.CharacterSetTypeB\x03\xe0A\x03R\x10characterSetType\x12(\n" +
	"\rcharacter_set\x18\x03 \x01(\tB\x03\xe0A\x03R\fcharacterSet\"R\n" +
	"\x10CharacterSetType\x12\"\n" +
	"\x1eCHARACTER_SET_TYPE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bDATABASE\x10\x01\x12\f\n" +
	"\bNATIONAL\x10\x02:\xf0\x01\xeaA\xec\x01\n" +
	"<oracledatabase.googleapis.com/AutonomousDatabaseCharacterSet\x12kprojects/{project}/locations/{location}/autonomousDatabaseCharacterSets/{autonomous_database_character_set}*\x1fautonomousDatabaseCharacterSets2\x1eautonomousDatabaseCharacterSetB\xfd\x01\n" +
	"\"com.google.cloud.oracledatabase.v1B#AutonomousDatabaseCharacterSetProtoP\x01ZJcloud.google.com/go/oracledatabase/apiv1/oracledatabasepb;oracledatabasepb\xaa\x02\x1eGoogle.Cloud.OracleDatabase.V1\xca\x02\x1eGoogle\\Cloud\\OracleDatabase\\V1\xea\x02!Google::Cloud::OracleDatabase::V1b\x06proto3"

var (
	file_google_cloud_oracledatabase_v1_autonomous_database_character_set_proto_rawDescOnce sync.Once
	file_google_cloud_oracledatabase_v1_autonomous_database_character_set_proto_rawDescData []byte
)

func file_google_cloud_oracledatabase_v1_autonomous_database_character_set_proto_rawDescGZIP() []byte {
	file_google_cloud_oracledatabase_v1_autonomous_database_character_set_proto_rawDescOnce.Do(func() {
		file_google_cloud_oracledatabase_v1_autonomous_database_character_set_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_cloud_oracledatabase_v1_autonomous_database_character_set_proto_rawDesc), len(file_google_cloud_oracledatabase_v1_autonomous_database_character_set_proto_rawDesc)))
	})
	return file_google_cloud_oracledatabase_v1_autonomous_database_character_set_proto_rawDescData
}

var file_google_cloud_oracledatabase_v1_autonomous_database_character_set_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_google_cloud_oracledatabase_v1_autonomous_database_character_set_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_google_cloud_oracledatabase_v1_autonomous_database_character_set_proto_goTypes = []any{
	(AutonomousDatabaseCharacterSet_CharacterSetType)(0), // 0: google.cloud.oracledatabase.v1.AutonomousDatabaseCharacterSet.CharacterSetType
	(*AutonomousDatabaseCharacterSet)(nil),               // 1: google.cloud.oracledatabase.v1.AutonomousDatabaseCharacterSet
}
var file_google_cloud_oracledatabase_v1_autonomous_database_character_set_proto_depIdxs = []int32{
	0, // 0: google.cloud.oracledatabase.v1.AutonomousDatabaseCharacterSet.character_set_type:type_name -> google.cloud.oracledatabase.v1.AutonomousDatabaseCharacterSet.CharacterSetType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_google_cloud_oracledatabase_v1_autonomous_database_character_set_proto_init() }
func file_google_cloud_oracledatabase_v1_autonomous_database_character_set_proto_init() {
	if File_google_cloud_oracledatabase_v1_autonomous_database_character_set_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_cloud_oracledatabase_v1_autonomous_database_character_set_proto_rawDesc), len(file_google_cloud_oracledatabase_v1_autonomous_database_character_set_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_cloud_oracledatabase_v1_autonomous_database_character_set_proto_goTypes,
		DependencyIndexes: file_google_cloud_oracledatabase_v1_autonomous_database_character_set_proto_depIdxs,
		EnumInfos:         file_google_cloud_oracledatabase_v1_autonomous_database_character_set_proto_enumTypes,
		MessageInfos:      file_google_cloud_oracledatabase_v1_autonomous_database_character_set_proto_msgTypes,
	}.Build()
	File_google_cloud_oracledatabase_v1_autonomous_database_character_set_proto = out.File
	file_google_cloud_oracledatabase_v1_autonomous_database_character_set_proto_goTypes = nil
	file_google_cloud_oracledatabase_v1_autonomous_database_character_set_proto_depIdxs = nil
}
