docker:
  image: gcr.io/cloud-devrel-public-resources/owlbot-go:latest

deep-remove-regex:
  - /bigquery/analyticshub/apiv1/
  - /bigquery/biglake/apiv1/
  - /bigquery/biglake/apiv1alpha1/
  - /bigquery/connection/apiv1/
  - /bigquery/connection/apiv1beta1/
  - /bigquery/dataexchange/apiv1beta1/
  - /bigquery/datapolicies/apiv1/
  - /bigquery/datapolicies/apiv1beta1/
  - /bigquery/datapolicies/apiv2/
  - /bigquery/datapolicies/apiv2beta1/
  - /bigquery/datatransfer/apiv1/
  - /bigquery/migration/apiv2/
  - /bigquery/migration/apiv2alpha/
  - /bigquery/reservation/apiv1/
  - /bigquery/storage/apiv1/
  - /bigquery/storage/apiv1alpha/
  - /bigquery/storage/apiv1beta/
  - /bigquery/storage/apiv1beta1/
  - /bigquery/storage/apiv1beta2/
  - /bigquery/v2/apiv2/
  - /bigtable/admin/apiv2/
  - /bigtable/apiv2/
  # START snippets
  - /internal/generated/snippets/bigquery/analyticshub/apiv1/
  - /internal/generated/snippets/bigquery/biglake/apiv1/
  - /internal/generated/snippets/bigquery/biglake/apiv1alpha1/
  - /internal/generated/snippets/bigquery/connection/apiv1/
  - /internal/generated/snippets/bigquery/connection/apiv1beta1/
  - /internal/generated/snippets/bigquery/dataexchange/apiv1beta1/
  - /internal/generated/snippets/bigquery/datapolicies/apiv1/
  - /internal/generated/snippets/bigquery/datapolicies/apiv1beta1/
  - /internal/generated/snippets/bigquery/datapolicies/apiv2/
  - /internal/generated/snippets/bigquery/datapolicies/apiv2beta1/
  - /internal/generated/snippets/bigquery/datatransfer/apiv1/
  - /internal/generated/snippets/bigquery/migration/apiv2/
  - /internal/generated/snippets/bigquery/migration/apiv2alpha/
  - /internal/generated/snippets/bigquery/reservation/apiv1/
  - /internal/generated/snippets/bigquery/storage/apiv1/
  - /internal/generated/snippets/bigquery/storage/apiv1alpha/
  - /internal/generated/snippets/bigquery/storage/apiv1beta/
  - /internal/generated/snippets/bigquery/storage/apiv1beta1/
  - /internal/generated/snippets/bigquery/storage/apiv1beta2/
  - /internal/generated/snippets/bigquery/v2/apiv2/
  - /internal/generated/snippets//developerconnect/apiv1/
  - /internal/generated/snippets//devicestreaming/apiv1/
  - /internal/generated/snippets/storage/control/apiv2/
  # END snippets
  - /storage/control/apiv2/
  - /storage/internal/apiv2/

deep-preserve-regex:
  - /.*/info.go
  - /.*/path_funcs.go
  - /.*/version.go
  # TODO(#7336): Remove these networkconnectivity lines once breaking change is handled.
  - /storage/internal/apiv2/metadata.go
  # Must preserve these even though they aren't generated anymore

deep-copy-regex:
  # Just copy the bigtable protos for now
  - source: /google/bigtable/admin/v2/cloud.google.com/go/bigtable/admin/apiv2/adminpb
    dest: /bigtable/admin/apiv2/adminpb
  - source: /google/bigtable/v2/cloud.google.com/go/bigtable/apiv2/bigtablepb
    dest: /bigtable/apiv2/bigtablepb
  - source: /google/cloud/bigquery/analyticshub/v1/cloud.google.com/go
    dest: /
  - source: /google/cloud/bigquery/biglake/v1/cloud.google.com/go
    dest: /
  - source: /google/cloud/bigquery/biglake/v1alpha1/cloud.google.com/go
    dest: /
  - source: /google/cloud/bigquery/connection/v1/cloud.google.com/go
    dest: /
  - source: /google/cloud/bigquery/connection/v1beta1/cloud.google.com/go
    dest: /
  - source: /google/cloud/bigquery/dataexchange/v1beta1/cloud.google.com/go
    dest: /
  - source: /google/cloud/bigquery/datapolicies/v1/cloud.google.com/go
    dest: /
  - source: /google/cloud/bigquery/datapolicies/v1beta1/cloud.google.com/go
    dest: /
  - source: /google/cloud/bigquery/datapolicies/v2/cloud.google.com/go
    dest: /
  - source: /google/cloud/bigquery/datapolicies/v2beta1/cloud.google.com/go
    dest: /
  - source: /google/cloud/bigquery/datatransfer/v1/cloud.google.com/go
    dest: /
  - source: /google/cloud/bigquery/migration/v2/cloud.google.com/go
    dest: /
  - source: /google/cloud/bigquery/migration/v2alpha/cloud.google.com/go
    dest: /
  - source: /google/cloud/bigquery/reservation/v1/cloud.google.com/go
    dest: /
  - source: /google/cloud/bigquery/storage/v1/cloud.google.com/go
    dest: /
  - source: /google/cloud/bigquery/storage/v1alpha/cloud.google.com/go
    dest: /
  - source: /google/cloud/bigquery/storage/v1beta/cloud.google.com/go
    dest: /
  - source: /google/cloud/bigquery/storage/v1beta1/cloud.google.com/go
    dest: /
  - source: /google/cloud/bigquery/storage/v1beta2/cloud.google.com/go
    dest: /
  - source: /google/cloud/bigquery/v2/cloud.google.com/go
    dest: /
  - source: /google/storage/control/v2/cloud.google.com/go/
    dest: /
  - source: /google/storage/v2/cloud.google.com/go/storage/internal/apiv2
    dest: /storage/internal/apiv2
