docker:
  image: gcr.io/cloud-devrel-public-resources/owlbot-go:latest

deep-remove-regex:
  # START snippets
  - /internal/generated/snippets//developerconnect/apiv1/
  - /internal/generated/snippets//devicestreaming/apiv1/
  # END snippets

deep-preserve-regex:
  - /.*/info.go
  - /.*/path_funcs.go
  - /.*/version.go
