assign_issues_by:
- labels:
  - 'api: bigtable'
  - 'api: datastore'
  - 'api: firestore'
  to:
  - bhshkh
- labels:
  - 'api: storage'
  to:
  - BrennaEpp
- labels:
  - 'api: bigquery'
  to:
  - alvarowolfx
- labels:
  - 'api: pubsub'
  to:
  - hongalex
- labels:
  - 'api: pubsublite'
  to:
  - tmdiep
- labels:
  - 'api: spanner'
  to:
  - harshachinta
  - rahul2393
- labels:
  - 'api: logging'
  - 'api: clouderrorreporting'
  to:
  - googleapis/api-logging-go-reviewers
- labels:
  - 'api: cloudprofiler'
  to:
  - googleapis/api-profiler
