assign_issues_by:
- labels:
  - 'api: bigtable'
  to:
  - sushanb
- labels:
  - 'api: datastore'
  - 'api: firestore'
  to:
  - hongalex
  - shollyman
- labels:
  - 'api: storage'
  to:
  - cpriti-os
- labels:
  - 'api: pubsub'
  to:
  - hongalex
- labels:
  - 'api: pubsublite'
  to:
  - tmdiep
- labels:
  - 'api: spanner'
  to:
  - rahul2393
- labels:
  - 'api: cloudprofiler'
  to:
  - googleapis/api-profiler
