assign_issues_by:
- labels:
  - 'api: bigtable'
  - 'api: datastore'
  - 'api: firestore'
  to:
  - telpirion
- labels:
  - 'api: storage'
  to:
  - tritone
- labels:
  - 'api: bigquery'
  to:
  - shollyman
- labels:
  - 'api: pubsub'
  to:
  - hongalex
- labels:
  - 'api: spanner'
  to:
  - rahul2393
- labels:
  - 'api: logging'
  - 'api: clouderrorreporting'
  to:
  - googleapis/api-logging
