handleGHRelease: true
manifest: true

branches:
  - branch: main
    handleGHRelease: true
    manifest: true
    manifestFile: .release-please-manifest-submodules.json
    manifestConfig: release-please-config-submodules.json
  - branch: main
    handleGHRelease: true
    manifest: true
    manifestFile: .release-please-manifest-submodules.json
    manifestConfig: release-please-config-yoshi-submodules.json
  - branch: main
    handleGHRelease: true
    manifest: true
    manifestFile: bigquery/.release-please-manifest.json
    manifestConfig: bigquery/release-please-config.json
