# This file configures AppVeyor (http://www.appveyor.com),
# a Windows-based CI service similar to Travis.

# Identifier for this run
version: "{build}"

# Clone the repo into this path, which conforms to the standard
# Go workspace structure.
clone_folder: c:\gopath\src\cloud.google.com\go

environment:
  GOPATH: c:\gopath
  GCLOUD_TESTS_GOLANG_PROJECT_ID: dulcet-port-762
  GCLOUD_TESTS_GOLANG_KEY: key.json
  KEYFILE_CONTENTS:
    secure: jT/g1+p8ET+F9ozvHA3OD0h2ife1fx50AOHWb54PsvgO1J29E+HXZDL7osvFGnQBxC4Fz+Sr7QjG2o8TZXx9E8gIuN954xV3tXASTkC2VRL43zBrgbKf2ac3Yq6Q4XU0+W8ol4M4XxEm3M5YZ48nOa923RctC7JdXf/cAP04ReNBqgQAlHxCQWuBXtZjIsPOOC/OP55AO9BoFn8RTmEE/titnjrrqRo3CTyEUzvD6SVqoXbm7SVKDocPNppi1fMPHW8+0uLw2wvItr5etOE1t+6dOH4QoE2fKwC4SRPLK7N79mcVQX4ucMWJXPPvRqr4zZBlJGgLawAYhjCdH+hfN9KZjWVgS+PyzlNPFfPpBU/td8EMOws6A0uhcz+c/m9WCb2xqKjVBfbBp95u/XjStKyw43EW0ywsw8+NJckriW5cFbfwm01OwgKHIKBtQiGyNu7ULKRRYVWIfIP+5ZzSdIwcSWI6ieVoi6laIUXTIZapw5Mf6Ux2X+Azj7Goc+nGoNuyDpksAK7D/cumD7n7IufrnVF8Uoea4FlqeJ3Hq4bePT/fau3fzdJI+0iZeGtXWKSHBVfYjVI+ot5HrHvRGowP9DMuf4/9iC0NLWVuZOb6BWAhnzmxrRDMisPrnNDPEz66tc9508Fe6+BV51EZBj01qhHIx3RJnMzTp3MMT5YjaId46xqmOteWk2pq4FDpbsHG6HIL5WI673JeSSFhW3cPS1HaFOaFRe9ZxkE5Q3NNKJlBjp2Q3DTwqF/IlBNNt/Q4ygmBQ6BPuAh4fRidRLv8U4MGlZnlZbes/I+IgxutzKwz+JRUhG54ZfOq4QW+RYcR5j8e4neBBS9bNe4ga0rMkvHMWSo3o/3Ky+2iXMOTew2xjS5SmFbhcopGzWPzKKQkaEUmq0nPvJ6l1y+p7lfawuflRUcyU99Kf8CcP3eLnElkW27mKUcfIL/00VTy7lDuQwXX4Nhc1NwfPALySP9yxl1FnJA3cPvOfWPYeSFXOGGbDr2jC3MGEtQQZH4ZPml+RzKWq+ZRFkmgaCj4uyOMQb7zCncYAyixYAVrcnTiEFwZZE4vTP6RraQdeGJ3xKDyYG3gxMHP6iy+aQQ+1ujQlAgHrSnn4Nh10asXVBINSPXbqcx/jyBqcGA0zfwob542kB5XhC/3cUBGNp6SwztaE4IDryTJLGrrKetGdox7znVAKym/jT3N8+2fbNLIVS6ZiKa7O+cklt2WAwhbo5/5BJrpRkN8ZgbJDI0xFd/lH3S7D5qSfEoD4USdCYMsse27NYymn6pt4WZwrKplSLiFwpMkG53i5kwzysJPVUzXroHbZgNL5nmttIKbLVVyn+vVSS/0qrUW/P+6ThCBL6LsP/3UfJe/dV7+xkcYAnMnSM3Hd4E7qKGgclokajG5Cjgv5SzdFmYQHPtHKmmH/JypRJbplMolFCWzZ74AEWPrUzWqHxhZ+vHhBaQBYAdO/OpKr8YcljyGU9Fpq/9InXO10cUmTRQPf7bc1Ag3d+GJ7us/GXpQ5LJDzWNy6v6CMYk9GHkOUN3NhluD7e8C3u6Hj8Jl5rPq2I6a3qsj+6uAvXPwJ7TQR/dsZHa5D6cnbCUMSf/QqBn2PP3Q1PP5864f0lLBH1MywweIIjSS3JQ=

install:
  # Info for debugging.
  - echo %PATH%
  - go version
  - go env
  - go get -v -d -t ./...


# Provide a build script, or AppVeyor will call msbuild.
build_script:
  - go install -v ./...
  - echo %KEYFILE_CONTENTS% > %GCLOUD_TESTS_GOLANG_KEY%

test_script:
  - go test -v ./...
