// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go_gapic. DO NOT EDIT.

package testing

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"math"
	"net/http"
	"net/url"
	"time"

	gax "github.com/googleapis/gax-go/v2"
	"google.golang.org/api/googleapi"
	"google.golang.org/api/option"
	"google.golang.org/api/option/internaloption"
	gtransport "google.golang.org/api/transport/grpc"
	httptransport "google.golang.org/api/transport/http"
	testingpb "google.golang.org/genproto/googleapis/devtools/testing/v1"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/encoding/protojson"
)

var newApplicationDetailClientHook clientHook

// ApplicationDetailCallOptions contains the retry settings for each method of ApplicationDetailClient.
type ApplicationDetailCallOptions struct {
	GetApkDetails []gax.CallOption
}

func defaultApplicationDetailGRPCClientOptions() []option.ClientOption {
	return []option.ClientOption{
		internaloption.WithDefaultEndpoint("testing.googleapis.com:443"),
		internaloption.WithDefaultEndpointTemplate("testing.UNIVERSE_DOMAIN:443"),
		internaloption.WithDefaultMTLSEndpoint("testing.mtls.googleapis.com:443"),
		internaloption.WithDefaultUniverseDomain("googleapis.com"),
		internaloption.WithDefaultAudience("https://testing.googleapis.com/"),
		internaloption.WithDefaultScopes(DefaultAuthScopes()...),
		internaloption.EnableJwtWithScope(),
		internaloption.EnableNewAuthLibrary(),
		option.WithGRPCDialOption(grpc.WithDefaultCallOptions(
			grpc.MaxCallRecvMsgSize(math.MaxInt32))),
	}
}

func defaultApplicationDetailCallOptions() *ApplicationDetailCallOptions {
	return &ApplicationDetailCallOptions{
		GetApkDetails: []gax.CallOption{
			gax.WithTimeout(60000 * time.Millisecond),
		},
	}
}

func defaultApplicationDetailRESTCallOptions() *ApplicationDetailCallOptions {
	return &ApplicationDetailCallOptions{
		GetApkDetails: []gax.CallOption{
			gax.WithTimeout(60000 * time.Millisecond),
		},
	}
}

// internalApplicationDetailClient is an interface that defines the methods available from Cloud Testing API.
type internalApplicationDetailClient interface {
	Close() error
	setGoogleClientInfo(...string)
	Connection() *grpc.ClientConn
	GetApkDetails(context.Context, *testingpb.GetApkDetailsRequest, ...gax.CallOption) (*testingpb.GetApkDetailsResponse, error)
}

// ApplicationDetailClient is a client for interacting with Cloud Testing API.
// Methods, except Close, may be called concurrently. However, fields must not be modified concurrently with method calls.
//
// A service which parses input applications and returns details that can be
// useful in the context of testing.
type ApplicationDetailClient struct {
	// The internal transport-dependent client.
	internalClient internalApplicationDetailClient

	// The call options for this service.
	CallOptions *ApplicationDetailCallOptions
}

// Wrapper methods routed to the internal client.

// Close closes the connection to the API service. The user should invoke this when
// the client is no longer required.
func (c *ApplicationDetailClient) Close() error {
	return c.internalClient.Close()
}

// setGoogleClientInfo sets the name and version of the application in
// the `x-goog-api-client` header passed on each request. Intended for
// use by Google-written clients.
func (c *ApplicationDetailClient) setGoogleClientInfo(keyval ...string) {
	c.internalClient.setGoogleClientInfo(keyval...)
}

// Connection returns a connection to the API service.
//
// Deprecated: Connections are now pooled so this method does not always
// return the same resource.
func (c *ApplicationDetailClient) Connection() *grpc.ClientConn {
	return c.internalClient.Connection()
}

// GetApkDetails gets the details of an Android application APK.
func (c *ApplicationDetailClient) GetApkDetails(ctx context.Context, req *testingpb.GetApkDetailsRequest, opts ...gax.CallOption) (*testingpb.GetApkDetailsResponse, error) {
	return c.internalClient.GetApkDetails(ctx, req, opts...)
}

// applicationDetailGRPCClient is a client for interacting with Cloud Testing API over gRPC transport.
//
// Methods, except Close, may be called concurrently. However, fields must not be modified concurrently with method calls.
type applicationDetailGRPCClient struct {
	// Connection pool of gRPC connections to the service.
	connPool gtransport.ConnPool

	// Points back to the CallOptions field of the containing ApplicationDetailClient
	CallOptions **ApplicationDetailCallOptions

	// The gRPC API client.
	applicationDetailClient testingpb.ApplicationDetailServiceClient

	// The x-goog-* metadata to be sent with each request.
	xGoogHeaders []string
}

// NewApplicationDetailClient creates a new application detail service client based on gRPC.
// The returned client must be Closed when it is done being used to clean up its underlying connections.
//
// A service which parses input applications and returns details that can be
// useful in the context of testing.
func NewApplicationDetailClient(ctx context.Context, opts ...option.ClientOption) (*ApplicationDetailClient, error) {
	clientOpts := defaultApplicationDetailGRPCClientOptions()
	if newApplicationDetailClientHook != nil {
		hookOpts, err := newApplicationDetailClientHook(ctx, clientHookParams{})
		if err != nil {
			return nil, err
		}
		clientOpts = append(clientOpts, hookOpts...)
	}

	connPool, err := gtransport.DialPool(ctx, append(clientOpts, opts...)...)
	if err != nil {
		return nil, err
	}
	client := ApplicationDetailClient{CallOptions: defaultApplicationDetailCallOptions()}

	c := &applicationDetailGRPCClient{
		connPool:                connPool,
		applicationDetailClient: testingpb.NewApplicationDetailServiceClient(connPool),
		CallOptions:             &client.CallOptions,
	}
	c.setGoogleClientInfo()

	client.internalClient = c

	return &client, nil
}

// Connection returns a connection to the API service.
//
// Deprecated: Connections are now pooled so this method does not always
// return the same resource.
func (c *applicationDetailGRPCClient) Connection() *grpc.ClientConn {
	return c.connPool.Conn()
}

// setGoogleClientInfo sets the name and version of the application in
// the `x-goog-api-client` header passed on each request. Intended for
// use by Google-written clients.
func (c *applicationDetailGRPCClient) setGoogleClientInfo(keyval ...string) {
	kv := append([]string{"gl-go", gax.GoVersion}, keyval...)
	kv = append(kv, "gapic", getVersionClient(), "gax", gax.Version, "grpc", grpc.Version)
	c.xGoogHeaders = []string{
		"x-goog-api-client", gax.XGoogHeader(kv...),
	}
}

// Close closes the connection to the API service. The user should invoke this when
// the client is no longer required.
func (c *applicationDetailGRPCClient) Close() error {
	return c.connPool.Close()
}

// Methods, except Close, may be called concurrently. However, fields must not be modified concurrently with method calls.
type applicationDetailRESTClient struct {
	// The http endpoint to connect to.
	endpoint string

	// The http client.
	httpClient *http.Client

	// The x-goog-* headers to be sent with each request.
	xGoogHeaders []string

	// Points back to the CallOptions field of the containing ApplicationDetailClient
	CallOptions **ApplicationDetailCallOptions
}

// NewApplicationDetailRESTClient creates a new application detail service rest client.
//
// A service which parses input applications and returns details that can be
// useful in the context of testing.
func NewApplicationDetailRESTClient(ctx context.Context, opts ...option.ClientOption) (*ApplicationDetailClient, error) {
	clientOpts := append(defaultApplicationDetailRESTClientOptions(), opts...)
	httpClient, endpoint, err := httptransport.NewClient(ctx, clientOpts...)
	if err != nil {
		return nil, err
	}

	callOpts := defaultApplicationDetailRESTCallOptions()
	c := &applicationDetailRESTClient{
		endpoint:    endpoint,
		httpClient:  httpClient,
		CallOptions: &callOpts,
	}
	c.setGoogleClientInfo()

	return &ApplicationDetailClient{internalClient: c, CallOptions: callOpts}, nil
}

func defaultApplicationDetailRESTClientOptions() []option.ClientOption {
	return []option.ClientOption{
		internaloption.WithDefaultEndpoint("https://testing.googleapis.com"),
		internaloption.WithDefaultEndpointTemplate("https://testing.UNIVERSE_DOMAIN"),
		internaloption.WithDefaultMTLSEndpoint("https://testing.mtls.googleapis.com"),
		internaloption.WithDefaultUniverseDomain("googleapis.com"),
		internaloption.WithDefaultAudience("https://testing.googleapis.com/"),
		internaloption.WithDefaultScopes(DefaultAuthScopes()...),
		internaloption.EnableNewAuthLibrary(),
	}
}

// setGoogleClientInfo sets the name and version of the application in
// the `x-goog-api-client` header passed on each request. Intended for
// use by Google-written clients.
func (c *applicationDetailRESTClient) setGoogleClientInfo(keyval ...string) {
	kv := append([]string{"gl-go", gax.GoVersion}, keyval...)
	kv = append(kv, "gapic", getVersionClient(), "gax", gax.Version, "rest", "UNKNOWN")
	c.xGoogHeaders = []string{
		"x-goog-api-client", gax.XGoogHeader(kv...),
	}
}

// Close closes the connection to the API service. The user should invoke this when
// the client is no longer required.
func (c *applicationDetailRESTClient) Close() error {
	// Replace httpClient with nil to force cleanup.
	c.httpClient = nil
	return nil
}

// Connection returns a connection to the API service.
//
// Deprecated: This method always returns nil.
func (c *applicationDetailRESTClient) Connection() *grpc.ClientConn {
	return nil
}
func (c *applicationDetailGRPCClient) GetApkDetails(ctx context.Context, req *testingpb.GetApkDetailsRequest, opts ...gax.CallOption) (*testingpb.GetApkDetailsResponse, error) {
	ctx = gax.InsertMetadataIntoOutgoingContext(ctx, c.xGoogHeaders...)
	opts = append((*c.CallOptions).GetApkDetails[0:len((*c.CallOptions).GetApkDetails):len((*c.CallOptions).GetApkDetails)], opts...)
	var resp *testingpb.GetApkDetailsResponse
	err := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
		var err error
		resp, err = c.applicationDetailClient.GetApkDetails(ctx, req, settings.GRPC...)
		return err
	}, opts...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

// GetApkDetails gets the details of an Android application APK.
func (c *applicationDetailRESTClient) GetApkDetails(ctx context.Context, req *testingpb.GetApkDetailsRequest, opts ...gax.CallOption) (*testingpb.GetApkDetailsResponse, error) {
	m := protojson.MarshalOptions{AllowPartial: true, UseEnumNumbers: true}
	body := req.GetLocation()
	jsonReq, err := m.Marshal(body)
	if err != nil {
		return nil, err
	}

	baseUrl, err := url.Parse(c.endpoint)
	if err != nil {
		return nil, err
	}
	baseUrl.Path += fmt.Sprintf("/v1/applicationDetailService/getApkDetails")

	params := url.Values{}
	params.Add("$alt", "json;enum-encoding=int")
	if req.GetBundleLocation().GetGcsPath() != "" {
		params.Add("bundleLocation.gcsPath", fmt.Sprintf("%v", req.GetBundleLocation().GetGcsPath()))
	}

	baseUrl.RawQuery = params.Encode()

	// Build HTTP headers from client and context metadata.
	hds := append(c.xGoogHeaders, "Content-Type", "application/json")
	headers := gax.BuildHeaders(ctx, hds...)
	opts = append((*c.CallOptions).GetApkDetails[0:len((*c.CallOptions).GetApkDetails):len((*c.CallOptions).GetApkDetails)], opts...)
	unm := protojson.UnmarshalOptions{AllowPartial: true, DiscardUnknown: true}
	resp := &testingpb.GetApkDetailsResponse{}
	e := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
		if settings.Path != "" {
			baseUrl.Path = settings.Path
		}
		httpReq, err := http.NewRequest("POST", baseUrl.String(), bytes.NewReader(jsonReq))
		if err != nil {
			return err
		}
		httpReq = httpReq.WithContext(ctx)
		httpReq.Header = headers

		httpRsp, err := c.httpClient.Do(httpReq)
		if err != nil {
			return err
		}
		defer httpRsp.Body.Close()

		if err = googleapi.CheckResponse(httpRsp); err != nil {
			return err
		}

		buf, err := io.ReadAll(httpRsp.Body)
		if err != nil {
			return err
		}

		if err := unm.Unmarshal(buf, resp); err != nil {
			return err
		}

		return nil
	}, opts...)
	if e != nil {
		return nil, e
	}
	return resp, nil
}
