// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.7
// source: google/cloud/bigquery/v2/decimal_target_types.proto

package bigquerypb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The data types that could be used as a target type when converting decimal
// values.
type DecimalTargetType int32

const (
	// Invalid type.
	DecimalTargetType_DECIMAL_TARGET_TYPE_UNSPECIFIED DecimalTargetType = 0
	// Decimal values could be converted to NUMERIC
	// type.
	DecimalTargetType_NUMERIC DecimalTargetType = 1
	// Decimal values could be converted to BIGNUMERIC
	// type.
	DecimalTargetType_BIGNUMERIC DecimalTargetType = 2
	// Decimal values could be converted to STRING type.
	DecimalTargetType_STRING DecimalTargetType = 3
)

// Enum value maps for DecimalTargetType.
var (
	DecimalTargetType_name = map[int32]string{
		0: "DECIMAL_TARGET_TYPE_UNSPECIFIED",
		1: "NUMERIC",
		2: "BIGNUMERIC",
		3: "STRING",
	}
	DecimalTargetType_value = map[string]int32{
		"DECIMAL_TARGET_TYPE_UNSPECIFIED": 0,
		"NUMERIC":                         1,
		"BIGNUMERIC":                      2,
		"STRING":                          3,
	}
)

func (x DecimalTargetType) Enum() *DecimalTargetType {
	p := new(DecimalTargetType)
	*p = x
	return p
}

func (x DecimalTargetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DecimalTargetType) Descriptor() protoreflect.EnumDescriptor {
	return file_google_cloud_bigquery_v2_decimal_target_types_proto_enumTypes[0].Descriptor()
}

func (DecimalTargetType) Type() protoreflect.EnumType {
	return &file_google_cloud_bigquery_v2_decimal_target_types_proto_enumTypes[0]
}

func (x DecimalTargetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DecimalTargetType.Descriptor instead.
func (DecimalTargetType) EnumDescriptor() ([]byte, []int) {
	return file_google_cloud_bigquery_v2_decimal_target_types_proto_rawDescGZIP(), []int{0}
}

var File_google_cloud_bigquery_v2_decimal_target_types_proto protoreflect.FileDescriptor

const file_google_cloud_bigquery_v2_decimal_target_types_proto_rawDesc = "" +
	"\n" +
	"3google/cloud/bigquery/v2/decimal_target_types.proto\x12\x18google.cloud.bigquery.v2*a\n" +
	"\x11DecimalTargetType\x12#\n" +
	"\x1fDECIMAL_TARGET_TYPE_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aNUMERIC\x10\x01\x12\x0e\n" +
	"\n" +
	"BIGNUMERIC\x10\x02\x12\n" +
	"\n" +
	"\x06STRING\x10\x03Bv\n" +
	"\x1ccom.google.cloud.bigquery.v2B\x17DecimalTargetTypesProtoP\x01Z;cloud.google.com/go/bigquery/v2/apiv2/bigquerypb;bigquerypbb\x06proto3"

var (
	file_google_cloud_bigquery_v2_decimal_target_types_proto_rawDescOnce sync.Once
	file_google_cloud_bigquery_v2_decimal_target_types_proto_rawDescData []byte
)

func file_google_cloud_bigquery_v2_decimal_target_types_proto_rawDescGZIP() []byte {
	file_google_cloud_bigquery_v2_decimal_target_types_proto_rawDescOnce.Do(func() {
		file_google_cloud_bigquery_v2_decimal_target_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_cloud_bigquery_v2_decimal_target_types_proto_rawDesc), len(file_google_cloud_bigquery_v2_decimal_target_types_proto_rawDesc)))
	})
	return file_google_cloud_bigquery_v2_decimal_target_types_proto_rawDescData
}

var file_google_cloud_bigquery_v2_decimal_target_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_google_cloud_bigquery_v2_decimal_target_types_proto_goTypes = []any{
	(DecimalTargetType)(0), // 0: google.cloud.bigquery.v2.DecimalTargetType
}
var file_google_cloud_bigquery_v2_decimal_target_types_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_google_cloud_bigquery_v2_decimal_target_types_proto_init() }
func file_google_cloud_bigquery_v2_decimal_target_types_proto_init() {
	if File_google_cloud_bigquery_v2_decimal_target_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_cloud_bigquery_v2_decimal_target_types_proto_rawDesc), len(file_google_cloud_bigquery_v2_decimal_target_types_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_cloud_bigquery_v2_decimal_target_types_proto_goTypes,
		DependencyIndexes: file_google_cloud_bigquery_v2_decimal_target_types_proto_depIdxs,
		EnumInfos:         file_google_cloud_bigquery_v2_decimal_target_types_proto_enumTypes,
	}.Build()
	File_google_cloud_bigquery_v2_decimal_target_types_proto = out.File
	file_google_cloud_bigquery_v2_decimal_target_types_proto_goTypes = nil
	file_google_cloud_bigquery_v2_decimal_target_types_proto_depIdxs = nil
}
