// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.0
// source: google/cloud/datacatalog/v1/tags.proto

package datacatalogpb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This enum describes TagTemplate transfer status to Dataplex service.
type TagTemplate_DataplexTransferStatus int32

const (
	// Default value. TagTemplate and its tags are only visible and editable in
	// DataCatalog.
	TagTemplate_DATAPLEX_TRANSFER_STATUS_UNSPECIFIED TagTemplate_DataplexTransferStatus = 0
	// TagTemplate and its tags are auto-copied to Dataplex service.
	// Visible in both services. Editable in DataCatalog, read-only in Dataplex.
	// Deprecated: Individual TagTemplate migration is deprecated in favor of
	// organization or project wide TagTemplate migration opt-in.
	//
	// Deprecated: Marked as deprecated in google/cloud/datacatalog/v1/tags.proto.
	TagTemplate_MIGRATED TagTemplate_DataplexTransferStatus = 1
	// TagTemplate and its tags are auto-copied to Dataplex service.
	// Visible in both services. Editable in Dataplex, read-only in DataCatalog.
	TagTemplate_TRANSFERRED TagTemplate_DataplexTransferStatus = 2
)

// Enum value maps for TagTemplate_DataplexTransferStatus.
var (
	TagTemplate_DataplexTransferStatus_name = map[int32]string{
		0: "DATAPLEX_TRANSFER_STATUS_UNSPECIFIED",
		1: "MIGRATED",
		2: "TRANSFERRED",
	}
	TagTemplate_DataplexTransferStatus_value = map[string]int32{
		"DATAPLEX_TRANSFER_STATUS_UNSPECIFIED": 0,
		"MIGRATED":                             1,
		"TRANSFERRED":                          2,
	}
)

func (x TagTemplate_DataplexTransferStatus) Enum() *TagTemplate_DataplexTransferStatus {
	p := new(TagTemplate_DataplexTransferStatus)
	*p = x
	return p
}

func (x TagTemplate_DataplexTransferStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TagTemplate_DataplexTransferStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_google_cloud_datacatalog_v1_tags_proto_enumTypes[0].Descriptor()
}

func (TagTemplate_DataplexTransferStatus) Type() protoreflect.EnumType {
	return &file_google_cloud_datacatalog_v1_tags_proto_enumTypes[0]
}

func (x TagTemplate_DataplexTransferStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TagTemplate_DataplexTransferStatus.Descriptor instead.
func (TagTemplate_DataplexTransferStatus) EnumDescriptor() ([]byte, []int) {
	return file_google_cloud_datacatalog_v1_tags_proto_rawDescGZIP(), []int{2, 0}
}

type FieldType_PrimitiveType int32

const (
	// The default invalid value for a type.
	FieldType_PRIMITIVE_TYPE_UNSPECIFIED FieldType_PrimitiveType = 0
	// A double precision number.
	FieldType_DOUBLE FieldType_PrimitiveType = 1
	// An UTF-8 string.
	FieldType_STRING FieldType_PrimitiveType = 2
	// A boolean value.
	FieldType_BOOL FieldType_PrimitiveType = 3
	// A timestamp.
	FieldType_TIMESTAMP FieldType_PrimitiveType = 4
	// A Richtext description.
	FieldType_RICHTEXT FieldType_PrimitiveType = 5
)

// Enum value maps for FieldType_PrimitiveType.
var (
	FieldType_PrimitiveType_name = map[int32]string{
		0: "PRIMITIVE_TYPE_UNSPECIFIED",
		1: "DOUBLE",
		2: "STRING",
		3: "BOOL",
		4: "TIMESTAMP",
		5: "RICHTEXT",
	}
	FieldType_PrimitiveType_value = map[string]int32{
		"PRIMITIVE_TYPE_UNSPECIFIED": 0,
		"DOUBLE":                     1,
		"STRING":                     2,
		"BOOL":                       3,
		"TIMESTAMP":                  4,
		"RICHTEXT":                   5,
	}
)

func (x FieldType_PrimitiveType) Enum() *FieldType_PrimitiveType {
	p := new(FieldType_PrimitiveType)
	*p = x
	return p
}

func (x FieldType_PrimitiveType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FieldType_PrimitiveType) Descriptor() protoreflect.EnumDescriptor {
	return file_google_cloud_datacatalog_v1_tags_proto_enumTypes[1].Descriptor()
}

func (FieldType_PrimitiveType) Type() protoreflect.EnumType {
	return &file_google_cloud_datacatalog_v1_tags_proto_enumTypes[1]
}

func (x FieldType_PrimitiveType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FieldType_PrimitiveType.Descriptor instead.
func (FieldType_PrimitiveType) EnumDescriptor() ([]byte, []int) {
	return file_google_cloud_datacatalog_v1_tags_proto_rawDescGZIP(), []int{4, 0}
}

// Tags contain custom metadata and are attached to Data Catalog resources. Tags
// conform with the specification of their tag template.
//
// See [Data Catalog
// IAM](https://cloud.google.com/data-catalog/docs/concepts/iam) for information
// on the permissions needed to create or view tags.
type Tag struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier. The resource name of the tag in URL format where tag ID is a
	// system-generated identifier.
	//
	// Note: The tag itself might not be stored in the location specified in its
	// name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Required. The resource name of the tag template this tag uses. Example:
	//
	// `projects/{PROJECT_ID}/locations/{LOCATION}/tagTemplates/{TAG_TEMPLATE_ID}`
	//
	// This field cannot be modified after creation.
	Template string `protobuf:"bytes,2,opt,name=template,proto3" json:"template,omitempty"`
	// Output only. The display name of the tag template.
	TemplateDisplayName string `protobuf:"bytes,5,opt,name=template_display_name,json=templateDisplayName,proto3" json:"template_display_name,omitempty"`
	// The scope within the parent resource that this tag is attached to. If not
	// provided, the tag is attached to the parent resource itself.
	//
	// Deleting the scope from the parent resource deletes all tags attached
	// to that scope.
	//
	// These fields cannot be updated after creation.
	//
	// Types that are valid to be assigned to Scope:
	//
	//	*Tag_Column
	Scope isTag_Scope `protobuf_oneof:"scope"`
	// Required. Maps the ID of a tag field to its value and additional
	// information about that field.
	//
	// Tag template defines valid field IDs. A tag
	// must have at least 1 field and at most 500 fields.
	Fields map[string]*TagField `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Output only. Denotes the transfer status of the Tag Template.
	DataplexTransferStatus TagTemplate_DataplexTransferStatus `protobuf:"varint,7,opt,name=dataplex_transfer_status,json=dataplexTransferStatus,proto3,enum=google.cloud.datacatalog.v1.TagTemplate_DataplexTransferStatus" json:"dataplex_transfer_status,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_google_cloud_datacatalog_v1_tags_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_datacatalog_v1_tags_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_google_cloud_datacatalog_v1_tags_proto_rawDescGZIP(), []int{0}
}

func (x *Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tag) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *Tag) GetTemplateDisplayName() string {
	if x != nil {
		return x.TemplateDisplayName
	}
	return ""
}

func (x *Tag) GetScope() isTag_Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *Tag) GetColumn() string {
	if x != nil {
		if x, ok := x.Scope.(*Tag_Column); ok {
			return x.Column
		}
	}
	return ""
}

func (x *Tag) GetFields() map[string]*TagField {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Tag) GetDataplexTransferStatus() TagTemplate_DataplexTransferStatus {
	if x != nil {
		return x.DataplexTransferStatus
	}
	return TagTemplate_DATAPLEX_TRANSFER_STATUS_UNSPECIFIED
}

type isTag_Scope interface {
	isTag_Scope()
}

type Tag_Column struct {
	// Resources like entry can have schemas associated with them. This scope
	// allows you to attach tags to an individual column based on that schema.
	//
	// To attach a tag to a nested column, separate column names with a dot
	// (`.`). Example: `column.nested_column`.
	Column string `protobuf:"bytes,4,opt,name=column,proto3,oneof"`
}

func (*Tag_Column) isTag_Scope() {}

// Contains the value and additional information on a field within
// a [Tag][google.cloud.datacatalog.v1.Tag].
type TagField struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Output only. The display name of this field.
	DisplayName string `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Required. The value of this field.
	//
	// Types that are valid to be assigned to Kind:
	//
	//	*TagField_DoubleValue
	//	*TagField_StringValue
	//	*TagField_BoolValue
	//	*TagField_TimestampValue
	//	*TagField_EnumValue_
	//	*TagField_RichtextValue
	Kind isTagField_Kind `protobuf_oneof:"kind"`
	// Output only. The order of this field with respect to other fields in this
	// tag. Can be set by
	// [Tag][google.cloud.datacatalog.v1.TagTemplateField.order].
	//
	// For example, a higher value can indicate a more important field.
	// The value can be negative. Multiple fields can have the same order, and
	// field orders within a tag don't have to be sequential.
	Order         int32 `protobuf:"varint,7,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagField) Reset() {
	*x = TagField{}
	mi := &file_google_cloud_datacatalog_v1_tags_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagField) ProtoMessage() {}

func (x *TagField) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_datacatalog_v1_tags_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagField.ProtoReflect.Descriptor instead.
func (*TagField) Descriptor() ([]byte, []int) {
	return file_google_cloud_datacatalog_v1_tags_proto_rawDescGZIP(), []int{1}
}

func (x *TagField) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *TagField) GetKind() isTagField_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *TagField) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Kind.(*TagField_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *TagField) GetStringValue() string {
	if x != nil {
		if x, ok := x.Kind.(*TagField_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *TagField) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Kind.(*TagField_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *TagField) GetTimestampValue() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.Kind.(*TagField_TimestampValue); ok {
			return x.TimestampValue
		}
	}
	return nil
}

func (x *TagField) GetEnumValue() *TagField_EnumValue {
	if x != nil {
		if x, ok := x.Kind.(*TagField_EnumValue_); ok {
			return x.EnumValue
		}
	}
	return nil
}

func (x *TagField) GetRichtextValue() string {
	if x != nil {
		if x, ok := x.Kind.(*TagField_RichtextValue); ok {
			return x.RichtextValue
		}
	}
	return ""
}

func (x *TagField) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

type isTagField_Kind interface {
	isTagField_Kind()
}

type TagField_DoubleValue struct {
	// The value of a tag field with a double type.
	DoubleValue float64 `protobuf:"fixed64,2,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type TagField_StringValue struct {
	// The value of a tag field with a string type.
	//
	// The maximum length is 2000 UTF-8 characters.
	StringValue string `protobuf:"bytes,3,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type TagField_BoolValue struct {
	// The value of a tag field with a boolean type.
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type TagField_TimestampValue struct {
	// The value of a tag field with a timestamp type.
	TimestampValue *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp_value,json=timestampValue,proto3,oneof"`
}

type TagField_EnumValue_ struct {
	// The value of a tag field with an enum type.
	//
	// This value must be one of the allowed values listed in this enum.
	EnumValue *TagField_EnumValue `protobuf:"bytes,6,opt,name=enum_value,json=enumValue,proto3,oneof"`
}

type TagField_RichtextValue struct {
	// The value of a tag field with a rich text type.
	//
	// The maximum length is 10 MiB as this value holds HTML descriptions
	// including encoded images. The maximum length of the text without images
	// is 100 KiB.
	RichtextValue string `protobuf:"bytes,8,opt,name=richtext_value,json=richtextValue,proto3,oneof"`
}

func (*TagField_DoubleValue) isTagField_Kind() {}

func (*TagField_StringValue) isTagField_Kind() {}

func (*TagField_BoolValue) isTagField_Kind() {}

func (*TagField_TimestampValue) isTagField_Kind() {}

func (*TagField_EnumValue_) isTagField_Kind() {}

func (*TagField_RichtextValue) isTagField_Kind() {}

// A tag template defines a tag that can have one or more typed fields.
//
// The template is used to create tags that are attached to Google Cloud
//
//	resources. [Tag template roles]
//
// (https://cloud.google.com/iam/docs/understanding-roles#data-catalog-roles)
// provide permissions to create, edit, and use the template. For example,
// see the [TagTemplate User]
// (https://cloud.google.com/data-catalog/docs/how-to/template-user) role
// that includes a permission to use the tag template to tag resources.
type TagTemplate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier. The resource name of the tag template in URL format.
	//
	// Note: The tag template itself and its child resources might not be
	// stored in the location specified in its name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Display name for this template. Defaults to an empty string.
	//
	// The name must contain only Unicode letters, numbers (0-9), underscores (_),
	// dashes (-), spaces ( ), and can't start or end with spaces.
	// The maximum length is 200 characters.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Indicates whether tags created with this template are public. Public tags
	// do not require tag template access to appear in
	// [ListTags][google.cloud.datacatalog.v1.DataCatalog.ListTags] API response.
	//
	// Additionally, you can search for a public tag by value with a
	// simple search query in addition to using a “tag:“ predicate.
	IsPubliclyReadable bool `protobuf:"varint,5,opt,name=is_publicly_readable,json=isPubliclyReadable,proto3" json:"is_publicly_readable,omitempty"`
	// Required. Map of tag template field IDs to the settings for the field.
	// This map is an exhaustive list of the allowed fields. The map must contain
	// at least one field and at most 500 fields.
	//
	// The keys to this map are tag template field IDs. The IDs have the
	// following limitations:
	//
	//   - Can contain uppercase and lowercase letters, numbers (0-9) and
	//     underscores (_).
	//   - Must be at least 1 character and at most 64 characters long.
	//   - Must start with a letter or underscore.
	Fields map[string]*TagTemplateField `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Optional. Transfer status of the TagTemplate
	DataplexTransferStatus TagTemplate_DataplexTransferStatus `protobuf:"varint,7,opt,name=dataplex_transfer_status,json=dataplexTransferStatus,proto3,enum=google.cloud.datacatalog.v1.TagTemplate_DataplexTransferStatus" json:"dataplex_transfer_status,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TagTemplate) Reset() {
	*x = TagTemplate{}
	mi := &file_google_cloud_datacatalog_v1_tags_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagTemplate) ProtoMessage() {}

func (x *TagTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_datacatalog_v1_tags_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagTemplate.ProtoReflect.Descriptor instead.
func (*TagTemplate) Descriptor() ([]byte, []int) {
	return file_google_cloud_datacatalog_v1_tags_proto_rawDescGZIP(), []int{2}
}

func (x *TagTemplate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TagTemplate) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *TagTemplate) GetIsPubliclyReadable() bool {
	if x != nil {
		return x.IsPubliclyReadable
	}
	return false
}

func (x *TagTemplate) GetFields() map[string]*TagTemplateField {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *TagTemplate) GetDataplexTransferStatus() TagTemplate_DataplexTransferStatus {
	if x != nil {
		return x.DataplexTransferStatus
	}
	return TagTemplate_DATAPLEX_TRANSFER_STATUS_UNSPECIFIED
}

// The template for an individual field within a tag template.
type TagTemplateField struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier. The resource name of the tag template field in URL format.
	// Example:
	//
	// `projects/{PROJECT_ID}/locations/{LOCATION}/tagTemplates/{TAG_TEMPLATE}/fields/{FIELD}`
	//
	// Note: The tag template field itself might not be stored in the location
	// specified in its name.
	//
	// The name must contain only letters (a-z, A-Z), numbers (0-9),
	// or underscores (_), and must start with a letter or underscore.
	// The maximum length is 64 characters.
	Name string `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	// The display name for this field. Defaults to an empty string.
	//
	// The name must contain only Unicode letters, numbers (0-9), underscores (_),
	// dashes (-), spaces ( ), and can't start or end with spaces.
	// The maximum length is 200 characters.
	DisplayName string `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Required. The type of value this tag field can contain.
	Type *FieldType `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// If true, this field is required. Defaults to false.
	IsRequired bool `protobuf:"varint,3,opt,name=is_required,json=isRequired,proto3" json:"is_required,omitempty"`
	// The description for this field. Defaults to an empty string.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// The order of this field with respect to other fields in this tag
	// template.
	//
	// For example, a higher value can indicate a more important field.
	// The value can be negative. Multiple fields can have the same order and
	// field orders within a tag don't have to be sequential.
	Order         int32 `protobuf:"varint,5,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagTemplateField) Reset() {
	*x = TagTemplateField{}
	mi := &file_google_cloud_datacatalog_v1_tags_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagTemplateField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagTemplateField) ProtoMessage() {}

func (x *TagTemplateField) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_datacatalog_v1_tags_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagTemplateField.ProtoReflect.Descriptor instead.
func (*TagTemplateField) Descriptor() ([]byte, []int) {
	return file_google_cloud_datacatalog_v1_tags_proto_rawDescGZIP(), []int{3}
}

func (x *TagTemplateField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TagTemplateField) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *TagTemplateField) GetType() *FieldType {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *TagTemplateField) GetIsRequired() bool {
	if x != nil {
		return x.IsRequired
	}
	return false
}

func (x *TagTemplateField) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TagTemplateField) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

type FieldType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required.
	//
	// Types that are valid to be assigned to TypeDecl:
	//
	//	*FieldType_PrimitiveType_
	//	*FieldType_EnumType_
	TypeDecl      isFieldType_TypeDecl `protobuf_oneof:"type_decl"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldType) Reset() {
	*x = FieldType{}
	mi := &file_google_cloud_datacatalog_v1_tags_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldType) ProtoMessage() {}

func (x *FieldType) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_datacatalog_v1_tags_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldType.ProtoReflect.Descriptor instead.
func (*FieldType) Descriptor() ([]byte, []int) {
	return file_google_cloud_datacatalog_v1_tags_proto_rawDescGZIP(), []int{4}
}

func (x *FieldType) GetTypeDecl() isFieldType_TypeDecl {
	if x != nil {
		return x.TypeDecl
	}
	return nil
}

func (x *FieldType) GetPrimitiveType() FieldType_PrimitiveType {
	if x != nil {
		if x, ok := x.TypeDecl.(*FieldType_PrimitiveType_); ok {
			return x.PrimitiveType
		}
	}
	return FieldType_PRIMITIVE_TYPE_UNSPECIFIED
}

func (x *FieldType) GetEnumType() *FieldType_EnumType {
	if x != nil {
		if x, ok := x.TypeDecl.(*FieldType_EnumType_); ok {
			return x.EnumType
		}
	}
	return nil
}

type isFieldType_TypeDecl interface {
	isFieldType_TypeDecl()
}

type FieldType_PrimitiveType_ struct {
	// Primitive types, such as string, boolean, etc.
	PrimitiveType FieldType_PrimitiveType `protobuf:"varint,1,opt,name=primitive_type,json=primitiveType,proto3,enum=google.cloud.datacatalog.v1.FieldType_PrimitiveType,oneof"`
}

type FieldType_EnumType_ struct {
	// An enum type.
	EnumType *FieldType_EnumType `protobuf:"bytes,2,opt,name=enum_type,json=enumType,proto3,oneof"`
}

func (*FieldType_PrimitiveType_) isFieldType_TypeDecl() {}

func (*FieldType_EnumType_) isFieldType_TypeDecl() {}

// An enum value.
type TagField_EnumValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The display name of the enum value.
	DisplayName   string `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagField_EnumValue) Reset() {
	*x = TagField_EnumValue{}
	mi := &file_google_cloud_datacatalog_v1_tags_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagField_EnumValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagField_EnumValue) ProtoMessage() {}

func (x *TagField_EnumValue) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_datacatalog_v1_tags_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagField_EnumValue.ProtoReflect.Descriptor instead.
func (*TagField_EnumValue) Descriptor() ([]byte, []int) {
	return file_google_cloud_datacatalog_v1_tags_proto_rawDescGZIP(), []int{1, 0}
}

func (x *TagField_EnumValue) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type FieldType_EnumType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The set of allowed values for this enum.
	//
	// This set must not be empty and can include up to 100 allowed values.
	// The display names of the values in this set must not be empty and must
	// be case-insensitively unique within this set.
	//
	// The order of items in this set is preserved. This field can be used to
	// create, remove, and reorder enum values. To rename enum values, use the
	// `RenameTagTemplateFieldEnumValue` method.
	AllowedValues []*FieldType_EnumType_EnumValue `protobuf:"bytes,1,rep,name=allowed_values,json=allowedValues,proto3" json:"allowed_values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldType_EnumType) Reset() {
	*x = FieldType_EnumType{}
	mi := &file_google_cloud_datacatalog_v1_tags_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldType_EnumType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldType_EnumType) ProtoMessage() {}

func (x *FieldType_EnumType) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_datacatalog_v1_tags_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldType_EnumType.ProtoReflect.Descriptor instead.
func (*FieldType_EnumType) Descriptor() ([]byte, []int) {
	return file_google_cloud_datacatalog_v1_tags_proto_rawDescGZIP(), []int{4, 0}
}

func (x *FieldType_EnumType) GetAllowedValues() []*FieldType_EnumType_EnumValue {
	if x != nil {
		return x.AllowedValues
	}
	return nil
}

type FieldType_EnumType_EnumValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The display name of the enum value. Must not be an empty
	// string.
	//
	// The name must contain only Unicode letters, numbers (0-9), underscores
	// (_), dashes (-), spaces ( ), and can't start or end with spaces. The
	// maximum length is 200 characters.
	DisplayName   string `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldType_EnumType_EnumValue) Reset() {
	*x = FieldType_EnumType_EnumValue{}
	mi := &file_google_cloud_datacatalog_v1_tags_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldType_EnumType_EnumValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldType_EnumType_EnumValue) ProtoMessage() {}

func (x *FieldType_EnumType_EnumValue) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_datacatalog_v1_tags_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldType_EnumType_EnumValue.ProtoReflect.Descriptor instead.
func (*FieldType_EnumType_EnumValue) Descriptor() ([]byte, []int) {
	return file_google_cloud_datacatalog_v1_tags_proto_rawDescGZIP(), []int{4, 0, 0}
}

func (x *FieldType_EnumType_EnumValue) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

var File_google_cloud_datacatalog_v1_tags_proto protoreflect.FileDescriptor

const file_google_cloud_datacatalog_v1_tags_proto_rawDesc = "" +
	"\n" +
	"&google/cloud/datacatalog/v1/tags.proto\x12\x1bgoogle.cloud.datacatalog.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcc\x04\n" +
	"\x03Tag\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\bR\x04name\x12\x1f\n" +
	"\btemplate\x18\x02 \x01(\tB\x03\xe0A\x02R\btemplate\x127\n" +
	"\x15template_display_name\x18\x05 \x01(\tB\x03\xe0A\x03R\x13templateDisplayName\x12\x18\n" +
	"\x06column\x18\x04 \x01(\tH\x00R\x06column\x12I\n" +
	"\x06fields\x18\x03 \x03(\v2,.google.cloud.datacatalog.v1.Tag.FieldsEntryB\x03\xe0A\x02R\x06fields\x12~\n" +
	"\x18dataplex_transfer_status\x18\a \x01(\x0e2?.google.cloud.datacatalog.v1.TagTemplate.DataplexTransferStatusB\x03\xe0A\x03R\x16dataplexTransferStatus\x1a`\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12;\n" +
	"\x05value\x18\x02 \x01(\v2%.google.cloud.datacatalog.v1.TagFieldR\x05value:\x028\x01:\x81\x01\xeaA~\n" +
	"\x1edatacatalog.googleapis.com/Tag\x12\\projects/{project}/locations/{location}/entryGroups/{entry_group}/entries/{entry}/tags/{tag}B\a\n" +
	"\x05scope\"\xb2\x03\n" +
	"\bTagField\x12&\n" +
	"\fdisplay_name\x18\x01 \x01(\tB\x03\xe0A\x03R\vdisplayName\x12#\n" +
	"\fdouble_value\x18\x02 \x01(\x01H\x00R\vdoubleValue\x12#\n" +
	"\fstring_value\x18\x03 \x01(\tH\x00R\vstringValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x04 \x01(\bH\x00R\tboolValue\x12E\n" +
	"\x0ftimestamp_value\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x0etimestampValue\x12P\n" +
	"\n" +
	"enum_value\x18\x06 \x01(\v2/.google.cloud.datacatalog.v1.TagField.EnumValueH\x00R\tenumValue\x12'\n" +
	"\x0erichtext_value\x18\b \x01(\tH\x00R\rrichtextValue\x12\x19\n" +
	"\x05order\x18\a \x01(\x05B\x03\xe0A\x03R\x05order\x1a.\n" +
	"\tEnumValue\x12!\n" +
	"\fdisplay_name\x18\x01 \x01(\tR\vdisplayNameB\x06\n" +
	"\x04kind\"\x91\x05\n" +
	"\vTagTemplate\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\bR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x120\n" +
	"\x14is_publicly_readable\x18\x05 \x01(\bR\x12isPubliclyReadable\x12Q\n" +
	"\x06fields\x18\x03 \x03(\v24.google.cloud.datacatalog.v1.TagTemplate.FieldsEntryB\x03\xe0A\x02R\x06fields\x12~\n" +
	"\x18dataplex_transfer_status\x18\a \x01(\x0e2?.google.cloud.datacatalog.v1.TagTemplate.DataplexTransferStatusB\x03\xe0A\x01R\x16dataplexTransferStatus\x1ah\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12C\n" +
	"\x05value\x18\x02 \x01(\v2-.google.cloud.datacatalog.v1.TagTemplateFieldR\x05value:\x028\x01\"e\n" +
	"\x16DataplexTransferStatus\x12(\n" +
	"$DATAPLEX_TRANSFER_STATUS_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\bMIGRATED\x10\x01\x1a\x02\b\x01\x12\x0f\n" +
	"\vTRANSFERRED\x10\x02:p\xeaAm\n" +
	"&datacatalog.googleapis.com/TagTemplate\x12Cprojects/{project}/locations/{location}/tagTemplates/{tag_template}\"\xf0\x02\n" +
	"\x10TagTemplateField\x12\x17\n" +
	"\x04name\x18\x06 \x01(\tB\x03\xe0A\bR\x04name\x12!\n" +
	"\fdisplay_name\x18\x01 \x01(\tR\vdisplayName\x12?\n" +
	"\x04type\x18\x02 \x01(\v2&.google.cloud.datacatalog.v1.FieldTypeB\x03\xe0A\x02R\x04type\x12\x1f\n" +
	"\vis_required\x18\x03 \x01(\bR\n" +
	"isRequired\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05order\x18\x05 \x01(\x05R\x05order:\x85\x01\xeaA\x81\x01\n" +
	"+datacatalog.googleapis.com/TagTemplateField\x12Rprojects/{project}/locations/{location}/tagTemplates/{tag_template}/fields/{field}\"\xdb\x03\n" +
	"\tFieldType\x12]\n" +
	"\x0eprimitive_type\x18\x01 \x01(\x0e24.google.cloud.datacatalog.v1.FieldType.PrimitiveTypeH\x00R\rprimitiveType\x12N\n" +
	"\tenum_type\x18\x02 \x01(\v2/.google.cloud.datacatalog.v1.FieldType.EnumTypeH\x00R\benumType\x1a\xa1\x01\n" +
	"\bEnumType\x12`\n" +
	"\x0eallowed_values\x18\x01 \x03(\v29.google.cloud.datacatalog.v1.FieldType.EnumType.EnumValueR\rallowedValues\x1a3\n" +
	"\tEnumValue\x12&\n" +
	"\fdisplay_name\x18\x01 \x01(\tB\x03\xe0A\x02R\vdisplayName\"n\n" +
	"\rPrimitiveType\x12\x1e\n" +
	"\x1aPRIMITIVE_TYPE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06DOUBLE\x10\x01\x12\n" +
	"\n" +
	"\x06STRING\x10\x02\x12\b\n" +
	"\x04BOOL\x10\x03\x12\r\n" +
	"\tTIMESTAMP\x10\x04\x12\f\n" +
	"\bRICHTEXT\x10\x05B\v\n" +
	"\ttype_declB\xc3\x01\n" +
	"\x1fcom.google.cloud.datacatalog.v1P\x01ZAcloud.google.com/go/datacatalog/apiv1/datacatalogpb;datacatalogpb\xaa\x02\x1bGoogle.Cloud.DataCatalog.V1\xca\x02\x1bGoogle\\Cloud\\DataCatalog\\V1\xea\x02\x1eGoogle::Cloud::DataCatalog::V1b\x06proto3"

var (
	file_google_cloud_datacatalog_v1_tags_proto_rawDescOnce sync.Once
	file_google_cloud_datacatalog_v1_tags_proto_rawDescData []byte
)

func file_google_cloud_datacatalog_v1_tags_proto_rawDescGZIP() []byte {
	file_google_cloud_datacatalog_v1_tags_proto_rawDescOnce.Do(func() {
		file_google_cloud_datacatalog_v1_tags_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_cloud_datacatalog_v1_tags_proto_rawDesc), len(file_google_cloud_datacatalog_v1_tags_proto_rawDesc)))
	})
	return file_google_cloud_datacatalog_v1_tags_proto_rawDescData
}

var file_google_cloud_datacatalog_v1_tags_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_google_cloud_datacatalog_v1_tags_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_google_cloud_datacatalog_v1_tags_proto_goTypes = []any{
	(TagTemplate_DataplexTransferStatus)(0), // 0: google.cloud.datacatalog.v1.TagTemplate.DataplexTransferStatus
	(FieldType_PrimitiveType)(0),            // 1: google.cloud.datacatalog.v1.FieldType.PrimitiveType
	(*Tag)(nil),                             // 2: google.cloud.datacatalog.v1.Tag
	(*TagField)(nil),                        // 3: google.cloud.datacatalog.v1.TagField
	(*TagTemplate)(nil),                     // 4: google.cloud.datacatalog.v1.TagTemplate
	(*TagTemplateField)(nil),                // 5: google.cloud.datacatalog.v1.TagTemplateField
	(*FieldType)(nil),                       // 6: google.cloud.datacatalog.v1.FieldType
	nil,                                     // 7: google.cloud.datacatalog.v1.Tag.FieldsEntry
	(*TagField_EnumValue)(nil),              // 8: google.cloud.datacatalog.v1.TagField.EnumValue
	nil,                                     // 9: google.cloud.datacatalog.v1.TagTemplate.FieldsEntry
	(*FieldType_EnumType)(nil),              // 10: google.cloud.datacatalog.v1.FieldType.EnumType
	(*FieldType_EnumType_EnumValue)(nil),    // 11: google.cloud.datacatalog.v1.FieldType.EnumType.EnumValue
	(*timestamppb.Timestamp)(nil),           // 12: google.protobuf.Timestamp
}
var file_google_cloud_datacatalog_v1_tags_proto_depIdxs = []int32{
	7,  // 0: google.cloud.datacatalog.v1.Tag.fields:type_name -> google.cloud.datacatalog.v1.Tag.FieldsEntry
	0,  // 1: google.cloud.datacatalog.v1.Tag.dataplex_transfer_status:type_name -> google.cloud.datacatalog.v1.TagTemplate.DataplexTransferStatus
	12, // 2: google.cloud.datacatalog.v1.TagField.timestamp_value:type_name -> google.protobuf.Timestamp
	8,  // 3: google.cloud.datacatalog.v1.TagField.enum_value:type_name -> google.cloud.datacatalog.v1.TagField.EnumValue
	9,  // 4: google.cloud.datacatalog.v1.TagTemplate.fields:type_name -> google.cloud.datacatalog.v1.TagTemplate.FieldsEntry
	0,  // 5: google.cloud.datacatalog.v1.TagTemplate.dataplex_transfer_status:type_name -> google.cloud.datacatalog.v1.TagTemplate.DataplexTransferStatus
	6,  // 6: google.cloud.datacatalog.v1.TagTemplateField.type:type_name -> google.cloud.datacatalog.v1.FieldType
	1,  // 7: google.cloud.datacatalog.v1.FieldType.primitive_type:type_name -> google.cloud.datacatalog.v1.FieldType.PrimitiveType
	10, // 8: google.cloud.datacatalog.v1.FieldType.enum_type:type_name -> google.cloud.datacatalog.v1.FieldType.EnumType
	3,  // 9: google.cloud.datacatalog.v1.Tag.FieldsEntry.value:type_name -> google.cloud.datacatalog.v1.TagField
	5,  // 10: google.cloud.datacatalog.v1.TagTemplate.FieldsEntry.value:type_name -> google.cloud.datacatalog.v1.TagTemplateField
	11, // 11: google.cloud.datacatalog.v1.FieldType.EnumType.allowed_values:type_name -> google.cloud.datacatalog.v1.FieldType.EnumType.EnumValue
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_google_cloud_datacatalog_v1_tags_proto_init() }
func file_google_cloud_datacatalog_v1_tags_proto_init() {
	if File_google_cloud_datacatalog_v1_tags_proto != nil {
		return
	}
	file_google_cloud_datacatalog_v1_tags_proto_msgTypes[0].OneofWrappers = []any{
		(*Tag_Column)(nil),
	}
	file_google_cloud_datacatalog_v1_tags_proto_msgTypes[1].OneofWrappers = []any{
		(*TagField_DoubleValue)(nil),
		(*TagField_StringValue)(nil),
		(*TagField_BoolValue)(nil),
		(*TagField_TimestampValue)(nil),
		(*TagField_EnumValue_)(nil),
		(*TagField_RichtextValue)(nil),
	}
	file_google_cloud_datacatalog_v1_tags_proto_msgTypes[4].OneofWrappers = []any{
		(*FieldType_PrimitiveType_)(nil),
		(*FieldType_EnumType_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_cloud_datacatalog_v1_tags_proto_rawDesc), len(file_google_cloud_datacatalog_v1_tags_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_cloud_datacatalog_v1_tags_proto_goTypes,
		DependencyIndexes: file_google_cloud_datacatalog_v1_tags_proto_depIdxs,
		EnumInfos:         file_google_cloud_datacatalog_v1_tags_proto_enumTypes,
		MessageInfos:      file_google_cloud_datacatalog_v1_tags_proto_msgTypes,
	}.Build()
	File_google_cloud_datacatalog_v1_tags_proto = out.File
	file_google_cloud_datacatalog_v1_tags_proto_goTypes = nil
	file_google_cloud_datacatalog_v1_tags_proto_depIdxs = nil
}
