// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: google/cloud/secretmanager/v1/service.proto

package secretmanagerpb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	iampb "cloud.google.com/go/iam/apiv1/iampb"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for
// [SecretManagerService.ListSecrets][google.cloud.secretmanager.v1.SecretManagerService.ListSecrets].
type ListSecretsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The resource name of the project associated with the
	// [Secrets][google.cloud.secretmanager.v1.Secret], in the format `projects/*`
	// or `projects/*/locations/*`
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// Optional. The maximum number of results to be returned in a single page. If
	// set to 0, the server decides the number of results to return. If the
	// number is greater than 25000, it is capped at 25000.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Optional. Pagination token, returned earlier via
	// [ListSecretsResponse.next_page_token][google.cloud.secretmanager.v1.ListSecretsResponse.next_page_token].
	PageToken string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Optional. Filter string, adhering to the rules in
	// [List-operation
	// filtering](https://cloud.google.com/secret-manager/docs/filtering). List
	// only secrets matching the filter. If filter is empty, all secrets are
	// listed.
	Filter        string `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretsRequest) Reset() {
	*x = ListSecretsRequest{}
	mi := &file_google_cloud_secretmanager_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsRequest) ProtoMessage() {}

func (x *ListSecretsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_secretmanager_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretsRequest.ProtoReflect.Descriptor instead.
func (*ListSecretsRequest) Descriptor() ([]byte, []int) {
	return file_google_cloud_secretmanager_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListSecretsRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListSecretsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListSecretsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListSecretsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

// Response message for
// [SecretManagerService.ListSecrets][google.cloud.secretmanager.v1.SecretManagerService.ListSecrets].
type ListSecretsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of [Secrets][google.cloud.secretmanager.v1.Secret] sorted in
	// reverse by create_time (newest first).
	Secrets []*Secret `protobuf:"bytes,1,rep,name=secrets,proto3" json:"secrets,omitempty"`
	// A token to retrieve the next page of results. Pass this value in
	// [ListSecretsRequest.page_token][google.cloud.secretmanager.v1.ListSecretsRequest.page_token]
	// to retrieve the next page.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// The total number of [Secrets][google.cloud.secretmanager.v1.Secret] but 0
	// when the
	// [ListSecretsRequest.filter][google.cloud.secretmanager.v1.ListSecretsRequest.filter]
	// field is set.
	TotalSize     int32 `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretsResponse) Reset() {
	*x = ListSecretsResponse{}
	mi := &file_google_cloud_secretmanager_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsResponse) ProtoMessage() {}

func (x *ListSecretsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_secretmanager_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretsResponse.ProtoReflect.Descriptor instead.
func (*ListSecretsResponse) Descriptor() ([]byte, []int) {
	return file_google_cloud_secretmanager_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListSecretsResponse) GetSecrets() []*Secret {
	if x != nil {
		return x.Secrets
	}
	return nil
}

func (x *ListSecretsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListSecretsResponse) GetTotalSize() int32 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

// Request message for
// [SecretManagerService.CreateSecret][google.cloud.secretmanager.v1.SecretManagerService.CreateSecret].
type CreateSecretRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The resource name of the project to associate with the
	// [Secret][google.cloud.secretmanager.v1.Secret], in the format `projects/*`
	// or `projects/*/locations/*`.
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// Required. This must be unique within the project.
	//
	// A secret ID is a string with a maximum length of 255 characters and can
	// contain uppercase and lowercase letters, numerals, and the hyphen (`-`) and
	// underscore (`_`) characters.
	SecretId string `protobuf:"bytes,2,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	// Required. A [Secret][google.cloud.secretmanager.v1.Secret] with initial
	// field values.
	Secret        *Secret `protobuf:"bytes,3,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSecretRequest) Reset() {
	*x = CreateSecretRequest{}
	mi := &file_google_cloud_secretmanager_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecretRequest) ProtoMessage() {}

func (x *CreateSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_secretmanager_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSecretRequest.ProtoReflect.Descriptor instead.
func (*CreateSecretRequest) Descriptor() ([]byte, []int) {
	return file_google_cloud_secretmanager_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSecretRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *CreateSecretRequest) GetSecretId() string {
	if x != nil {
		return x.SecretId
	}
	return ""
}

func (x *CreateSecretRequest) GetSecret() *Secret {
	if x != nil {
		return x.Secret
	}
	return nil
}

// Request message for
// [SecretManagerService.AddSecretVersion][google.cloud.secretmanager.v1.SecretManagerService.AddSecretVersion].
type AddSecretVersionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The resource name of the
	// [Secret][google.cloud.secretmanager.v1.Secret] to associate with the
	// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion] in the format
	// `projects/*/secrets/*` or `projects/*/locations/*/secrets/*`.
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// Required. The secret payload of the
	// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion].
	Payload       *SecretPayload `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSecretVersionRequest) Reset() {
	*x = AddSecretVersionRequest{}
	mi := &file_google_cloud_secretmanager_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSecretVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSecretVersionRequest) ProtoMessage() {}

func (x *AddSecretVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_secretmanager_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSecretVersionRequest.ProtoReflect.Descriptor instead.
func (*AddSecretVersionRequest) Descriptor() ([]byte, []int) {
	return file_google_cloud_secretmanager_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *AddSecretVersionRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *AddSecretVersionRequest) GetPayload() *SecretPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Request message for
// [SecretManagerService.EnableManagedRotation][google.cloud.secretmanager.v1.SecretManagerService.EnableManagedRotation].
type EnableManagedRotationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The resource name of the
	// [Secret][google.cloud.secretmanager.v1.Secret] to associate with the
	// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion] in the format
	// `projects/*/secrets/*` or `projects/*/locations/*/secrets/*`.
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// The credentials required for Managed Rotation.
	// Right now, only Cloud SQL Single User credentials are supported.
	//
	// Types that are valid to be assigned to Credentials:
	//
	//	*EnableManagedRotationRequest_CloudSqlSingleUserCredentials
	Credentials   isEnableManagedRotationRequest_Credentials `protobuf_oneof:"credentials"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableManagedRotationRequest) Reset() {
	*x = EnableManagedRotationRequest{}
	mi := &file_google_cloud_secretmanager_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableManagedRotationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableManagedRotationRequest) ProtoMessage() {}

func (x *EnableManagedRotationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_secretmanager_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableManagedRotationRequest.ProtoReflect.Descriptor instead.
func (*EnableManagedRotationRequest) Descriptor() ([]byte, []int) {
	return file_google_cloud_secretmanager_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *EnableManagedRotationRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *EnableManagedRotationRequest) GetCredentials() isEnableManagedRotationRequest_Credentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *EnableManagedRotationRequest) GetCloudSqlSingleUserCredentials() *EnableManagedRotationRequest_CloudSQLSingleUserCredentials {
	if x != nil {
		if x, ok := x.Credentials.(*EnableManagedRotationRequest_CloudSqlSingleUserCredentials); ok {
			return x.CloudSqlSingleUserCredentials
		}
	}
	return nil
}

type isEnableManagedRotationRequest_Credentials interface {
	isEnableManagedRotationRequest_Credentials()
}

type EnableManagedRotationRequest_CloudSqlSingleUserCredentials struct {
	// Credentials required for Cloud SQL DB for Single user Managed Rotation.
	CloudSqlSingleUserCredentials *EnableManagedRotationRequest_CloudSQLSingleUserCredentials `protobuf:"bytes,2,opt,name=cloud_sql_single_user_credentials,json=cloudSqlSingleUserCredentials,proto3,oneof"`
}

func (*EnableManagedRotationRequest_CloudSqlSingleUserCredentials) isEnableManagedRotationRequest_Credentials() {
}

// Request message for
// [SecretManagerService.RotateSecret][google.cloud.secretmanager.v1.SecretManagerService.RotateSecret].
type RotateSecretRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The resource name of the
	// [Secret][google.cloud.secretmanager.v1.Secret] to associate with the
	// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion] in the format
	// `projects/*/secrets/*` or `projects/*/locations/*/secrets/*`.
	Parent        string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateSecretRequest) Reset() {
	*x = RotateSecretRequest{}
	mi := &file_google_cloud_secretmanager_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateSecretRequest) ProtoMessage() {}

func (x *RotateSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_secretmanager_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateSecretRequest.ProtoReflect.Descriptor instead.
func (*RotateSecretRequest) Descriptor() ([]byte, []int) {
	return file_google_cloud_secretmanager_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *RotateSecretRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

// Request message for
// [SecretManagerService.GetSecret][google.cloud.secretmanager.v1.SecretManagerService.GetSecret].
type GetSecretRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The resource name of the
	// [Secret][google.cloud.secretmanager.v1.Secret], in the format
	// `projects/*/secrets/*` or `projects/*/locations/*/secrets/*`.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretRequest) Reset() {
	*x = GetSecretRequest{}
	mi := &file_google_cloud_secretmanager_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretRequest) ProtoMessage() {}

func (x *GetSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_secretmanager_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretRequest.ProtoReflect.Descriptor instead.
func (*GetSecretRequest) Descriptor() ([]byte, []int) {
	return file_google_cloud_secretmanager_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetSecretRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Request message for
// [SecretManagerService.ListSecretVersions][google.cloud.secretmanager.v1.SecretManagerService.ListSecretVersions].
type ListSecretVersionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The resource name of the
	// [Secret][google.cloud.secretmanager.v1.Secret] associated with the
	// [SecretVersions][google.cloud.secretmanager.v1.SecretVersion] to list, in
	// the format `projects/*/secrets/*` or `projects/*/locations/*/secrets/*`.
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// Optional. The maximum number of results to be returned in a single page. If
	// set to 0, the server decides the number of results to return. If the
	// number is greater than 25000, it is capped at 25000.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Optional. Pagination token, returned earlier via
	// ListSecretVersionsResponse.next_page_token][].
	PageToken string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Optional. Filter string, adhering to the rules in
	// [List-operation
	// filtering](https://cloud.google.com/secret-manager/docs/filtering). List
	// only secret versions matching the filter. If filter is empty, all secret
	// versions are listed.
	Filter        string `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretVersionsRequest) Reset() {
	*x = ListSecretVersionsRequest{}
	mi := &file_google_cloud_secretmanager_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretVersionsRequest) ProtoMessage() {}

func (x *ListSecretVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_secretmanager_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretVersionsRequest.ProtoReflect.Descriptor instead.
func (*ListSecretVersionsRequest) Descriptor() ([]byte, []int) {
	return file_google_cloud_secretmanager_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *ListSecretVersionsRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListSecretVersionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListSecretVersionsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListSecretVersionsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

// Response message for
// [SecretManagerService.ListSecretVersions][google.cloud.secretmanager.v1.SecretManagerService.ListSecretVersions].
type ListSecretVersionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of [SecretVersions][google.cloud.secretmanager.v1.SecretVersion]
	// sorted in reverse by create_time (newest first).
	Versions []*SecretVersion `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	// A token to retrieve the next page of results. Pass this value in
	// [ListSecretVersionsRequest.page_token][google.cloud.secretmanager.v1.ListSecretVersionsRequest.page_token]
	// to retrieve the next page.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// The total number of
	// [SecretVersions][google.cloud.secretmanager.v1.SecretVersion] but 0 when
	// the
	// [ListSecretsRequest.filter][google.cloud.secretmanager.v1.ListSecretsRequest.filter]
	// field is set.
	TotalSize     int32 `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretVersionsResponse) Reset() {
	*x = ListSecretVersionsResponse{}
	mi := &file_google_cloud_secretmanager_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretVersionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretVersionsResponse) ProtoMessage() {}

func (x *ListSecretVersionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_secretmanager_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretVersionsResponse.ProtoReflect.Descriptor instead.
func (*ListSecretVersionsResponse) Descriptor() ([]byte, []int) {
	return file_google_cloud_secretmanager_v1_service_proto_rawDescGZIP(), []int{8}
}

func (x *ListSecretVersionsResponse) GetVersions() []*SecretVersion {
	if x != nil {
		return x.Versions
	}
	return nil
}

func (x *ListSecretVersionsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListSecretVersionsResponse) GetTotalSize() int32 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

// Request message for
// [SecretManagerService.GetSecretVersion][google.cloud.secretmanager.v1.SecretManagerService.GetSecretVersion].
type GetSecretVersionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The resource name of the
	// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion] in the format
	// `projects/*/secrets/*/versions/*` or
	// `projects/*/locations/*/secrets/*/versions/*`.
	//
	// `projects/*/secrets/*/versions/latest` or
	// `projects/*/locations/*/secrets/*/versions/latest` is an alias to the most
	// recently created
	// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion].
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretVersionRequest) Reset() {
	*x = GetSecretVersionRequest{}
	mi := &file_google_cloud_secretmanager_v1_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretVersionRequest) ProtoMessage() {}

func (x *GetSecretVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_secretmanager_v1_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretVersionRequest.ProtoReflect.Descriptor instead.
func (*GetSecretVersionRequest) Descriptor() ([]byte, []int) {
	return file_google_cloud_secretmanager_v1_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetSecretVersionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Request message for
// [SecretManagerService.UpdateSecret][google.cloud.secretmanager.v1.SecretManagerService.UpdateSecret].
type UpdateSecretRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. [Secret][google.cloud.secretmanager.v1.Secret] with updated field
	// values.
	Secret *Secret `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	// Required. Specifies the fields to be updated.
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSecretRequest) Reset() {
	*x = UpdateSecretRequest{}
	mi := &file_google_cloud_secretmanager_v1_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSecretRequest) ProtoMessage() {}

func (x *UpdateSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_secretmanager_v1_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSecretRequest.ProtoReflect.Descriptor instead.
func (*UpdateSecretRequest) Descriptor() ([]byte, []int) {
	return file_google_cloud_secretmanager_v1_service_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateSecretRequest) GetSecret() *Secret {
	if x != nil {
		return x.Secret
	}
	return nil
}

func (x *UpdateSecretRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// Request message for
// [SecretManagerService.AccessSecretVersion][google.cloud.secretmanager.v1.SecretManagerService.AccessSecretVersion].
type AccessSecretVersionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The resource name of the
	// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion] in the format
	// `projects/*/secrets/*/versions/*` or
	// `projects/*/locations/*/secrets/*/versions/*`.
	//
	// `projects/*/secrets/*/versions/latest` or
	// `projects/*/locations/*/secrets/*/versions/latest` is an alias to the most
	// recently created
	// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion].
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessSecretVersionRequest) Reset() {
	*x = AccessSecretVersionRequest{}
	mi := &file_google_cloud_secretmanager_v1_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessSecretVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessSecretVersionRequest) ProtoMessage() {}

func (x *AccessSecretVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_secretmanager_v1_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessSecretVersionRequest.ProtoReflect.Descriptor instead.
func (*AccessSecretVersionRequest) Descriptor() ([]byte, []int) {
	return file_google_cloud_secretmanager_v1_service_proto_rawDescGZIP(), []int{11}
}

func (x *AccessSecretVersionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Response message for
// [SecretManagerService.AccessSecretVersion][google.cloud.secretmanager.v1.SecretManagerService.AccessSecretVersion].
type AccessSecretVersionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the
	// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion] in the format
	// `projects/*/secrets/*/versions/*` or
	// `projects/*/locations/*/secrets/*/versions/*`.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Secret payload
	Payload       *SecretPayload `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessSecretVersionResponse) Reset() {
	*x = AccessSecretVersionResponse{}
	mi := &file_google_cloud_secretmanager_v1_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessSecretVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessSecretVersionResponse) ProtoMessage() {}

func (x *AccessSecretVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_secretmanager_v1_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessSecretVersionResponse.ProtoReflect.Descriptor instead.
func (*AccessSecretVersionResponse) Descriptor() ([]byte, []int) {
	return file_google_cloud_secretmanager_v1_service_proto_rawDescGZIP(), []int{12}
}

func (x *AccessSecretVersionResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AccessSecretVersionResponse) GetPayload() *SecretPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Request message for
// [SecretManagerService.DeleteSecret][google.cloud.secretmanager.v1.SecretManagerService.DeleteSecret].
type DeleteSecretRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The resource name of the
	// [Secret][google.cloud.secretmanager.v1.Secret] to delete in the format
	// `projects/*/secrets/*`.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Optional. Etag of the [Secret][google.cloud.secretmanager.v1.Secret]. The
	// request succeeds if it matches the etag of the currently stored secret
	// object. If the etag is omitted, the request succeeds.
	Etag          string `protobuf:"bytes,2,opt,name=etag,proto3" json:"etag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretRequest) Reset() {
	*x = DeleteSecretRequest{}
	mi := &file_google_cloud_secretmanager_v1_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretRequest) ProtoMessage() {}

func (x *DeleteSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_secretmanager_v1_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretRequest.ProtoReflect.Descriptor instead.
func (*DeleteSecretRequest) Descriptor() ([]byte, []int) {
	return file_google_cloud_secretmanager_v1_service_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteSecretRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteSecretRequest) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

// Request message for
// [SecretManagerService.DisableSecretVersion][google.cloud.secretmanager.v1.SecretManagerService.DisableSecretVersion].
type DisableSecretVersionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The resource name of the
	// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion] to disable in
	// the format `projects/*/secrets/*/versions/*` or
	// `projects/*/locations/*/secrets/*/versions/*`.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Optional. Etag of the
	// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion]. The request
	// succeeds if it matches the etag of the currently stored secret version
	// object. If the etag is omitted, the request succeeds.
	Etag          string `protobuf:"bytes,2,opt,name=etag,proto3" json:"etag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableSecretVersionRequest) Reset() {
	*x = DisableSecretVersionRequest{}
	mi := &file_google_cloud_secretmanager_v1_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableSecretVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableSecretVersionRequest) ProtoMessage() {}

func (x *DisableSecretVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_secretmanager_v1_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableSecretVersionRequest.ProtoReflect.Descriptor instead.
func (*DisableSecretVersionRequest) Descriptor() ([]byte, []int) {
	return file_google_cloud_secretmanager_v1_service_proto_rawDescGZIP(), []int{14}
}

func (x *DisableSecretVersionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DisableSecretVersionRequest) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

// Request message for
// [SecretManagerService.EnableSecretVersion][google.cloud.secretmanager.v1.SecretManagerService.EnableSecretVersion].
type EnableSecretVersionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The resource name of the
	// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion] to enable in
	// the format `projects/*/secrets/*/versions/*` or
	// `projects/*/locations/*/secrets/*/versions/*`.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Optional. Etag of the
	// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion]. The request
	// succeeds if it matches the etag of the currently stored secret version
	// object. If the etag is omitted, the request succeeds.
	Etag          string `protobuf:"bytes,2,opt,name=etag,proto3" json:"etag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableSecretVersionRequest) Reset() {
	*x = EnableSecretVersionRequest{}
	mi := &file_google_cloud_secretmanager_v1_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableSecretVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableSecretVersionRequest) ProtoMessage() {}

func (x *EnableSecretVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_secretmanager_v1_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableSecretVersionRequest.ProtoReflect.Descriptor instead.
func (*EnableSecretVersionRequest) Descriptor() ([]byte, []int) {
	return file_google_cloud_secretmanager_v1_service_proto_rawDescGZIP(), []int{15}
}

func (x *EnableSecretVersionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnableSecretVersionRequest) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

// Request message for
// [SecretManagerService.DestroySecretVersion][google.cloud.secretmanager.v1.SecretManagerService.DestroySecretVersion].
type DestroySecretVersionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The resource name of the
	// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion] to destroy in
	// the format `projects/*/secrets/*/versions/*` or
	// `projects/*/locations/*/secrets/*/versions/*`.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Optional. Etag of the
	// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion]. The request
	// succeeds if it matches the etag of the currently stored secret version
	// object. If the etag is omitted, the request succeeds.
	Etag          string `protobuf:"bytes,2,opt,name=etag,proto3" json:"etag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroySecretVersionRequest) Reset() {
	*x = DestroySecretVersionRequest{}
	mi := &file_google_cloud_secretmanager_v1_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroySecretVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroySecretVersionRequest) ProtoMessage() {}

func (x *DestroySecretVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_secretmanager_v1_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroySecretVersionRequest.ProtoReflect.Descriptor instead.
func (*DestroySecretVersionRequest) Descriptor() ([]byte, []int) {
	return file_google_cloud_secretmanager_v1_service_proto_rawDescGZIP(), []int{16}
}

func (x *DestroySecretVersionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DestroySecretVersionRequest) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

// These are the credentials required for Cloud SQL DB for Single user
// Managed Rotation.
type EnableManagedRotationRequest_CloudSQLSingleUserCredentials struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Instance ID of the Cloud SQL instance.
	InstanceId string `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	// Required. Username of the Cloud SQL instance.
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	// Optional. Password of the Cloud SQL instance. If this is not provided,
	// a random password will be generated.
	Password      string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableManagedRotationRequest_CloudSQLSingleUserCredentials) Reset() {
	*x = EnableManagedRotationRequest_CloudSQLSingleUserCredentials{}
	mi := &file_google_cloud_secretmanager_v1_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableManagedRotationRequest_CloudSQLSingleUserCredentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableManagedRotationRequest_CloudSQLSingleUserCredentials) ProtoMessage() {}

func (x *EnableManagedRotationRequest_CloudSQLSingleUserCredentials) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_secretmanager_v1_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableManagedRotationRequest_CloudSQLSingleUserCredentials.ProtoReflect.Descriptor instead.
func (*EnableManagedRotationRequest_CloudSQLSingleUserCredentials) Descriptor() ([]byte, []int) {
	return file_google_cloud_secretmanager_v1_service_proto_rawDescGZIP(), []int{4, 0}
}

func (x *EnableManagedRotationRequest_CloudSQLSingleUserCredentials) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *EnableManagedRotationRequest_CloudSQLSingleUserCredentials) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *EnableManagedRotationRequest_CloudSQLSingleUserCredentials) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

var File_google_cloud_secretmanager_v1_service_proto protoreflect.FileDescriptor

const file_google_cloud_secretmanager_v1_service_proto_rawDesc = "" +
	"\n" +
	"+google/cloud/secretmanager/v1/service.proto\x12\x1dgoogle.cloud.secretmanager.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a-google/cloud/secretmanager/v1/resources.proto\x1a\x1egoogle/iam/v1/iam_policy.proto\x1a\x1agoogle/iam/v1/policy.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\"\xbc\x01\n" +
	"\x12ListSecretsRequest\x12C\n" +
	"\x06parent\x18\x01 \x01(\tB+\xe0A\x02\xfaA%\x12#secretmanager.googleapis.com/SecretR\x06parent\x12 \n" +
	"\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01R\bpageSize\x12\"\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tB\x03\xe0A\x01R\tpageToken\x12\x1b\n" +
	"\x06filter\x18\x04 \x01(\tB\x03\xe0A\x01R\x06filter\"\x9d\x01\n" +
	"\x13ListSecretsResponse\x12?\n" +
	"\asecrets\x18\x01 \x03(\v2%.google.cloud.secretmanager.v1.SecretR\asecrets\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1d\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x05R\ttotalSize\"\xc0\x01\n" +
	"\x13CreateSecretRequest\x12C\n" +
	"\x06parent\x18\x01 \x01(\tB+\xe0A\x02\xfaA%\x12#secretmanager.googleapis.com/SecretR\x06parent\x12 \n" +
	"\tsecret_id\x18\x02 \x01(\tB\x03\xe0A\x02R\bsecretId\x12B\n" +
	"\x06secret\x18\x03 \x01(\v2%.google.cloud.secretmanager.v1.SecretB\x03\xe0A\x02R\x06secret\"\xab\x01\n" +
	"\x17AddSecretVersionRequest\x12C\n" +
	"\x06parent\x18\x01 \x01(\tB+\xe0A\x02\xfaA%\n" +
	"#secretmanager.googleapis.com/SecretR\x06parent\x12K\n" +
	"\apayload\x18\x02 \x01(\v2,.google.cloud.secretmanager.v1.SecretPayloadB\x03\xe0A\x02R\apayload\"\xa4\x03\n" +
	"\x1cEnableManagedRotationRequest\x12C\n" +
	"\x06parent\x18\x01 \x01(\tB+\xe0A\x02\xfaA%\n" +
	"#secretmanager.googleapis.com/SecretR\x06parent\x12\xa5\x01\n" +
	"!cloud_sql_single_user_credentials\x18\x02 \x01(\v2Y.google.cloud.secretmanager.v1.EnableManagedRotationRequest.CloudSQLSingleUserCredentialsH\x00R\x1dcloudSqlSingleUserCredentials\x1a\x87\x01\n" +
	"\x1dCloudSQLSingleUserCredentials\x12$\n" +
	"\vinstance_id\x18\x01 \x01(\tB\x03\xe0A\x02R\n" +
	"instanceId\x12\x1f\n" +
	"\busername\x18\x02 \x01(\tB\x03\xe0A\x02R\busername\x12\x1f\n" +
	"\bpassword\x18\x03 \x01(\tB\x03\xe0A\x01R\bpasswordB\r\n" +
	"\vcredentials\"Z\n" +
	"\x13RotateSecretRequest\x12C\n" +
	"\x06parent\x18\x01 \x01(\tB+\xe0A\x02\xfaA%\n" +
	"#secretmanager.googleapis.com/SecretR\x06parent\"S\n" +
	"\x10GetSecretRequest\x12?\n" +
	"\x04name\x18\x01 \x01(\tB+\xe0A\x02\xfaA%\n" +
	"#secretmanager.googleapis.com/SecretR\x04name\"\xc3\x01\n" +
	"\x19ListSecretVersionsRequest\x12C\n" +
	"\x06parent\x18\x01 \x01(\tB+\xe0A\x02\xfaA%\n" +
	"#secretmanager.googleapis.com/SecretR\x06parent\x12 \n" +
	"\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01R\bpageSize\x12\"\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tB\x03\xe0A\x01R\tpageToken\x12\x1b\n" +
	"\x06filter\x18\x04 \x01(\tB\x03\xe0A\x01R\x06filter\"\xad\x01\n" +
	"\x1aListSecretVersionsResponse\x12H\n" +
	"\bversions\x18\x01 \x03(\v2,.google.cloud.secretmanager.v1.SecretVersionR\bversions\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1d\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x05R\ttotalSize\"a\n" +
	"\x17GetSecretVersionRequest\x12F\n" +
	"\x04name\x18\x01 \x01(\tB2\xe0A\x02\xfaA,\n" +
	"*secretmanager.googleapis.com/SecretVersionR\x04name\"\x9b\x01\n" +
	"\x13UpdateSecretRequest\x12B\n" +
	"\x06secret\x18\x01 \x01(\v2%.google.cloud.secretmanager.v1.SecretB\x03\xe0A\x02R\x06secret\x12@\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02R\n" +
	"updateMask\"d\n" +
	"\x1aAccessSecretVersionRequest\x12F\n" +
	"\x04name\x18\x01 \x01(\tB2\xe0A\x02\xfaA,\n" +
	"*secretmanager.googleapis.com/SecretVersionR\x04name\"\xaa\x01\n" +
	"\x1bAccessSecretVersionResponse\x12C\n" +
	"\x04name\x18\x01 \x01(\tB/\xfaA,\n" +
	"*secretmanager.googleapis.com/SecretVersionR\x04name\x12F\n" +
	"\apayload\x18\x02 \x01(\v2,.google.cloud.secretmanager.v1.SecretPayloadR\apayload\"o\n" +
	"\x13DeleteSecretRequest\x12?\n" +
	"\x04name\x18\x01 \x01(\tB+\xe0A\x02\xfaA%\n" +
	"#secretmanager.googleapis.com/SecretR\x04name\x12\x17\n" +
	"\x04etag\x18\x02 \x01(\tB\x03\xe0A\x01R\x04etag\"~\n" +
	"\x1bDisableSecretVersionRequest\x12F\n" +
	"\x04name\x18\x01 \x01(\tB2\xe0A\x02\xfaA,\n" +
	"*secretmanager.googleapis.com/SecretVersionR\x04name\x12\x17\n" +
	"\x04etag\x18\x02 \x01(\tB\x03\xe0A\x01R\x04etag\"}\n" +
	"\x1aEnableSecretVersionRequest\x12F\n" +
	"\x04name\x18\x01 \x01(\tB2\xe0A\x02\xfaA,\n" +
	"*secretmanager.googleapis.com/SecretVersionR\x04name\x12\x17\n" +
	"\x04etag\x18\x02 \x01(\tB\x03\xe0A\x01R\x04etag\"~\n" +
	"\x1bDestroySecretVersionRequest\x12F\n" +
	"\x04name\x18\x01 \x01(\tB2\xe0A\x02\xfaA,\n" +
	"*secretmanager.googleapis.com/SecretVersionR\x04name\x12\x17\n" +
	"\x04etag\x18\x02 \x01(\tB\x03\xe0A\x01R\x04etag2\xa1!\n" +
	"\x14SecretManagerService\x12\xd5\x01\n" +
	"\vListSecrets\x121.google.cloud.secretmanager.v1.ListSecretsRequest\x1a2.google.cloud.secretmanager.v1.ListSecretsResponse\"_\xdaA\x06parent\x82\xd3\xe4\x93\x02PZ-\x12+/v1/{parent=projects/*/locations/*}/secrets\x12\x1f/v1/{parent=projects/*}/secrets\x12\xec\x01\n" +
	"\fCreateSecret\x122.google.cloud.secretmanager.v1.CreateSecretRequest\x1a%.google.cloud.secretmanager.v1.Secret\"\x80\x01\xdaA\x17parent,secret_id,secret\x82\xd3\xe4\x93\x02`:\x06secretZ5:\x06secret\"+/v1/{parent=projects/*/locations/*}/secrets\"\x1f/v1/{parent=projects/*}/secrets\x12\x82\x02\n" +
	"\x10AddSecretVersion\x126.google.cloud.secretmanager.v1.AddSecretVersionRequest\x1a,.google.cloud.secretmanager.v1.SecretVersion\"\x87\x01\xdaA\x0eparent,payload\x82\xd3\xe4\x93\x02p:\x01*Z=:\x01*\"8/v1/{parent=projects/*/locations/*/secrets/*}:addVersion\",/v1/{parent=projects/*/secrets/*}:addVersion\x12\xc2\x01\n" +
	"\tGetSecret\x12/.google.cloud.secretmanager.v1.GetSecretRequest\x1a%.google.cloud.secretmanager.v1.Secret\"]\xdaA\x04name\x82\xd3\xe4\x93\x02PZ-\x12+/v1/{name=projects/*/locations/*/secrets/*}\x12\x1f/v1/{name=projects/*/secrets/*}\x12\xf5\x01\n" +
	"\fUpdateSecret\x122.google.cloud.secretmanager.v1.UpdateSecretRequest\x1a%.google.cloud.secretmanager.v1.Secret\"\x89\x01\xdaA\x12secret,update_mask\x82\xd3\xe4\x93\x02n:\x06secretZ<:\x06secret22/v1/{secret.name=projects/*/locations/*/secrets/*}2&/v1/{secret.name=projects/*/secrets/*}\x12\xb9\x01\n" +
	"\fDeleteSecret\x122.google.cloud.secretmanager.v1.DeleteSecretRequest\x1a\x16.google.protobuf.Empty\"]\xdaA\x04name\x82\xd3\xe4\x93\x02PZ-*+/v1/{name=projects/*/locations/*/secrets/*}*\x1f/v1/{name=projects/*/secrets/*}\x12\x80\x02\n" +
	"\x12ListSecretVersions\x128.google.cloud.secretmanager.v1.ListSecretVersionsRequest\x1a9.google.cloud.secretmanager.v1.ListSecretVersionsResponse\"u\xdaA\x06parent\x82\xd3\xe4\x93\x02fZ8\x126/v1/{parent=projects/*/locations/*/secrets/*}/versions\x12*/v1/{parent=projects/*/secrets/*}/versions\x12\xed\x01\n" +
	"\x10GetSecretVersion\x126.google.cloud.secretmanager.v1.GetSecretVersionRequest\x1a,.google.cloud.secretmanager.v1.SecretVersion\"s\xdaA\x04name\x82\xd3\xe4\x93\x02fZ8\x126/v1/{name=projects/*/locations/*/secrets/*/versions/*}\x12*/v1/{name=projects/*/secrets/*/versions/*}\x12\x90\x02\n" +
	"\x13AccessSecretVersion\x129.google.cloud.secretmanager.v1.AccessSecretVersionRequest\x1a:.google.cloud.secretmanager.v1.AccessSecretVersionResponse\"\x81\x01\xdaA\x04name\x82\xd3\xe4\x93\x02tZ?\x12=/v1/{name=projects/*/locations/*/secrets/*/versions/*}:access\x121/v1/{name=projects/*/secrets/*/versions/*}:access\x12\x8c\x02\n" +
	"\x14DisableSecretVersion\x12:.google.cloud.secretmanager.v1.DisableSecretVersionRequest\x1a,.google.cloud.secretmanager.v1.SecretVersion\"\x89\x01\xdaA\x04name\x82\xd3\xe4\x93\x02|:\x01*ZC:\x01*\">/v1/{name=projects/*/locations/*/secrets/*/versions/*}:disable\"2/v1/{name=projects/*/secrets/*/versions/*}:disable\x12\x88\x02\n" +
	"\x13EnableSecretVersion\x129.google.cloud.secretmanager.v1.EnableSecretVersionRequest\x1a,.google.cloud.secretmanager.v1.SecretVersion\"\x87\x01\xdaA\x04name\x82\xd3\xe4\x93\x02z:\x01*ZB:\x01*\"=/v1/{name=projects/*/locations/*/secrets/*/versions/*}:enable\"1/v1/{name=projects/*/secrets/*/versions/*}:enable\x12\x8c\x02\n" +
	"\x14DestroySecretVersion\x12:.google.cloud.secretmanager.v1.DestroySecretVersionRequest\x1a,.google.cloud.secretmanager.v1.SecretVersion\"\x89\x01\xdaA\x04name\x82\xd3\xe4\x93\x02|:\x01*ZC:\x01*\">/v1/{name=projects/*/locations/*/secrets/*/versions/*}:destroy\"2/v1/{name=projects/*/secrets/*/versions/*}:destroy\x12\xc9\x01\n" +
	"\fSetIamPolicy\x12\".google.iam.v1.SetIamPolicyRequest\x1a\x15.google.iam.v1.Policy\"~\x82\xd3\xe4\x93\x02x:\x01*ZA:\x01*\"</v1/{resource=projects/*/locations/*/secrets/*}:setIamPolicy\"0/v1/{resource=projects/*/secrets/*}:setIamPolicy\x12\xc3\x01\n" +
	"\fGetIamPolicy\x12\".google.iam.v1.GetIamPolicyRequest\x1a\x15.google.iam.v1.Policy\"x\x82\xd3\xe4\x93\x02rZ>\x12</v1/{resource=projects/*/locations/*/secrets/*}:getIamPolicy\x120/v1/{resource=projects/*/secrets/*}:getIamPolicy\x12\xf7\x01\n" +
	"\x12TestIamPermissions\x12(.google.iam.v1.TestIamPermissionsRequest\x1a).google.iam.v1.TestIamPermissionsResponse\"\x8b\x01\x82\xd3\xe4\x93\x02\x84\x01:\x01*ZG:\x01*\"B/v1/{resource=projects/*/locations/*/secrets/*}:testIamPermissions\"6/v1/{resource=projects/*/secrets/*}:testIamPermissions\x12\xbd\x02\n" +
	"\x15EnableManagedRotation\x12;.google.cloud.secretmanager.v1.EnableManagedRotationRequest\x1a,.google.cloud.secretmanager.v1.SecretVersion\"\xb8\x01\xdaA(parent,cloud_sql_single_user_credentials\x82\xd3\xe4\x93\x02\x86\x01:\x01*ZH:\x01*\"C/v1/{parent=projects/*/locations/*/secrets/*}:enableManagedRotation\"7/v1/{parent=projects/*/secrets/*}:enableManagedRotation\x12\xf6\x01\n" +
	"\fRotateSecret\x122.google.cloud.secretmanager.v1.RotateSecretRequest\x1a,.google.cloud.secretmanager.v1.SecretVersion\"\x83\x01\xdaA\x06parent\x82\xd3\xe4\x93\x02t:\x01*Z?:\x01*\":/v1/{parent=projects/*/locations/*/secrets/*}:rotateSecret\"./v1/{parent=projects/*/secrets/*}:rotateSecret\x1aP\xcaA\x1csecretmanager.googleapis.com\xd2A.https://www.googleapis.com/auth/cloud-platformB\xe5\x01\n" +
	"!com.google.cloud.secretmanager.v1B\fServiceProtoP\x01ZGcloud.google.com/go/secretmanager/apiv1/secretmanagerpb;secretmanagerpb\xa2\x02\x03GSM\xaa\x02\x1dGoogle.Cloud.SecretManager.V1\xca\x02\x1dGoogle\\Cloud\\SecretManager\\V1\xea\x02 Google::Cloud::SecretManager::V1b\x06proto3"

var (
	file_google_cloud_secretmanager_v1_service_proto_rawDescOnce sync.Once
	file_google_cloud_secretmanager_v1_service_proto_rawDescData []byte
)

func file_google_cloud_secretmanager_v1_service_proto_rawDescGZIP() []byte {
	file_google_cloud_secretmanager_v1_service_proto_rawDescOnce.Do(func() {
		file_google_cloud_secretmanager_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_cloud_secretmanager_v1_service_proto_rawDesc), len(file_google_cloud_secretmanager_v1_service_proto_rawDesc)))
	})
	return file_google_cloud_secretmanager_v1_service_proto_rawDescData
}

var file_google_cloud_secretmanager_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_google_cloud_secretmanager_v1_service_proto_goTypes = []any{
	(*ListSecretsRequest)(nil),                                         // 0: google.cloud.secretmanager.v1.ListSecretsRequest
	(*ListSecretsResponse)(nil),                                        // 1: google.cloud.secretmanager.v1.ListSecretsResponse
	(*CreateSecretRequest)(nil),                                        // 2: google.cloud.secretmanager.v1.CreateSecretRequest
	(*AddSecretVersionRequest)(nil),                                    // 3: google.cloud.secretmanager.v1.AddSecretVersionRequest
	(*EnableManagedRotationRequest)(nil),                               // 4: google.cloud.secretmanager.v1.EnableManagedRotationRequest
	(*RotateSecretRequest)(nil),                                        // 5: google.cloud.secretmanager.v1.RotateSecretRequest
	(*GetSecretRequest)(nil),                                           // 6: google.cloud.secretmanager.v1.GetSecretRequest
	(*ListSecretVersionsRequest)(nil),                                  // 7: google.cloud.secretmanager.v1.ListSecretVersionsRequest
	(*ListSecretVersionsResponse)(nil),                                 // 8: google.cloud.secretmanager.v1.ListSecretVersionsResponse
	(*GetSecretVersionRequest)(nil),                                    // 9: google.cloud.secretmanager.v1.GetSecretVersionRequest
	(*UpdateSecretRequest)(nil),                                        // 10: google.cloud.secretmanager.v1.UpdateSecretRequest
	(*AccessSecretVersionRequest)(nil),                                 // 11: google.cloud.secretmanager.v1.AccessSecretVersionRequest
	(*AccessSecretVersionResponse)(nil),                                // 12: google.cloud.secretmanager.v1.AccessSecretVersionResponse
	(*DeleteSecretRequest)(nil),                                        // 13: google.cloud.secretmanager.v1.DeleteSecretRequest
	(*DisableSecretVersionRequest)(nil),                                // 14: google.cloud.secretmanager.v1.DisableSecretVersionRequest
	(*EnableSecretVersionRequest)(nil),                                 // 15: google.cloud.secretmanager.v1.EnableSecretVersionRequest
	(*DestroySecretVersionRequest)(nil),                                // 16: google.cloud.secretmanager.v1.DestroySecretVersionRequest
	(*EnableManagedRotationRequest_CloudSQLSingleUserCredentials)(nil), // 17: google.cloud.secretmanager.v1.EnableManagedRotationRequest.CloudSQLSingleUserCredentials
	(*Secret)(nil),                                                     // 18: google.cloud.secretmanager.v1.Secret
	(*SecretPayload)(nil),                                              // 19: google.cloud.secretmanager.v1.SecretPayload
	(*SecretVersion)(nil),                                              // 20: google.cloud.secretmanager.v1.SecretVersion
	(*fieldmaskpb.FieldMask)(nil),                                      // 21: google.protobuf.FieldMask
	(*iampb.SetIamPolicyRequest)(nil),                                  // 22: google.iam.v1.SetIamPolicyRequest
	(*iampb.GetIamPolicyRequest)(nil),                                  // 23: google.iam.v1.GetIamPolicyRequest
	(*iampb.TestIamPermissionsRequest)(nil),                            // 24: google.iam.v1.TestIamPermissionsRequest
	(*emptypb.Empty)(nil),                                              // 25: google.protobuf.Empty
	(*iampb.Policy)(nil),                                               // 26: google.iam.v1.Policy
	(*iampb.TestIamPermissionsResponse)(nil),                           // 27: google.iam.v1.TestIamPermissionsResponse
}
var file_google_cloud_secretmanager_v1_service_proto_depIdxs = []int32{
	18, // 0: google.cloud.secretmanager.v1.ListSecretsResponse.secrets:type_name -> google.cloud.secretmanager.v1.Secret
	18, // 1: google.cloud.secretmanager.v1.CreateSecretRequest.secret:type_name -> google.cloud.secretmanager.v1.Secret
	19, // 2: google.cloud.secretmanager.v1.AddSecretVersionRequest.payload:type_name -> google.cloud.secretmanager.v1.SecretPayload
	17, // 3: google.cloud.secretmanager.v1.EnableManagedRotationRequest.cloud_sql_single_user_credentials:type_name -> google.cloud.secretmanager.v1.EnableManagedRotationRequest.CloudSQLSingleUserCredentials
	20, // 4: google.cloud.secretmanager.v1.ListSecretVersionsResponse.versions:type_name -> google.cloud.secretmanager.v1.SecretVersion
	18, // 5: google.cloud.secretmanager.v1.UpdateSecretRequest.secret:type_name -> google.cloud.secretmanager.v1.Secret
	21, // 6: google.cloud.secretmanager.v1.UpdateSecretRequest.update_mask:type_name -> google.protobuf.FieldMask
	19, // 7: google.cloud.secretmanager.v1.AccessSecretVersionResponse.payload:type_name -> google.cloud.secretmanager.v1.SecretPayload
	0,  // 8: google.cloud.secretmanager.v1.SecretManagerService.ListSecrets:input_type -> google.cloud.secretmanager.v1.ListSecretsRequest
	2,  // 9: google.cloud.secretmanager.v1.SecretManagerService.CreateSecret:input_type -> google.cloud.secretmanager.v1.CreateSecretRequest
	3,  // 10: google.cloud.secretmanager.v1.SecretManagerService.AddSecretVersion:input_type -> google.cloud.secretmanager.v1.AddSecretVersionRequest
	6,  // 11: google.cloud.secretmanager.v1.SecretManagerService.GetSecret:input_type -> google.cloud.secretmanager.v1.GetSecretRequest
	10, // 12: google.cloud.secretmanager.v1.SecretManagerService.UpdateSecret:input_type -> google.cloud.secretmanager.v1.UpdateSecretRequest
	13, // 13: google.cloud.secretmanager.v1.SecretManagerService.DeleteSecret:input_type -> google.cloud.secretmanager.v1.DeleteSecretRequest
	7,  // 14: google.cloud.secretmanager.v1.SecretManagerService.ListSecretVersions:input_type -> google.cloud.secretmanager.v1.ListSecretVersionsRequest
	9,  // 15: google.cloud.secretmanager.v1.SecretManagerService.GetSecretVersion:input_type -> google.cloud.secretmanager.v1.GetSecretVersionRequest
	11, // 16: google.cloud.secretmanager.v1.SecretManagerService.AccessSecretVersion:input_type -> google.cloud.secretmanager.v1.AccessSecretVersionRequest
	14, // 17: google.cloud.secretmanager.v1.SecretManagerService.DisableSecretVersion:input_type -> google.cloud.secretmanager.v1.DisableSecretVersionRequest
	15, // 18: google.cloud.secretmanager.v1.SecretManagerService.EnableSecretVersion:input_type -> google.cloud.secretmanager.v1.EnableSecretVersionRequest
	16, // 19: google.cloud.secretmanager.v1.SecretManagerService.DestroySecretVersion:input_type -> google.cloud.secretmanager.v1.DestroySecretVersionRequest
	22, // 20: google.cloud.secretmanager.v1.SecretManagerService.SetIamPolicy:input_type -> google.iam.v1.SetIamPolicyRequest
	23, // 21: google.cloud.secretmanager.v1.SecretManagerService.GetIamPolicy:input_type -> google.iam.v1.GetIamPolicyRequest
	24, // 22: google.cloud.secretmanager.v1.SecretManagerService.TestIamPermissions:input_type -> google.iam.v1.TestIamPermissionsRequest
	4,  // 23: google.cloud.secretmanager.v1.SecretManagerService.EnableManagedRotation:input_type -> google.cloud.secretmanager.v1.EnableManagedRotationRequest
	5,  // 24: google.cloud.secretmanager.v1.SecretManagerService.RotateSecret:input_type -> google.cloud.secretmanager.v1.RotateSecretRequest
	1,  // 25: google.cloud.secretmanager.v1.SecretManagerService.ListSecrets:output_type -> google.cloud.secretmanager.v1.ListSecretsResponse
	18, // 26: google.cloud.secretmanager.v1.SecretManagerService.CreateSecret:output_type -> google.cloud.secretmanager.v1.Secret
	20, // 27: google.cloud.secretmanager.v1.SecretManagerService.AddSecretVersion:output_type -> google.cloud.secretmanager.v1.SecretVersion
	18, // 28: google.cloud.secretmanager.v1.SecretManagerService.GetSecret:output_type -> google.cloud.secretmanager.v1.Secret
	18, // 29: google.cloud.secretmanager.v1.SecretManagerService.UpdateSecret:output_type -> google.cloud.secretmanager.v1.Secret
	25, // 30: google.cloud.secretmanager.v1.SecretManagerService.DeleteSecret:output_type -> google.protobuf.Empty
	8,  // 31: google.cloud.secretmanager.v1.SecretManagerService.ListSecretVersions:output_type -> google.cloud.secretmanager.v1.ListSecretVersionsResponse
	20, // 32: google.cloud.secretmanager.v1.SecretManagerService.GetSecretVersion:output_type -> google.cloud.secretmanager.v1.SecretVersion
	12, // 33: google.cloud.secretmanager.v1.SecretManagerService.AccessSecretVersion:output_type -> google.cloud.secretmanager.v1.AccessSecretVersionResponse
	20, // 34: google.cloud.secretmanager.v1.SecretManagerService.DisableSecretVersion:output_type -> google.cloud.secretmanager.v1.SecretVersion
	20, // 35: google.cloud.secretmanager.v1.SecretManagerService.EnableSecretVersion:output_type -> google.cloud.secretmanager.v1.SecretVersion
	20, // 36: google.cloud.secretmanager.v1.SecretManagerService.DestroySecretVersion:output_type -> google.cloud.secretmanager.v1.SecretVersion
	26, // 37: google.cloud.secretmanager.v1.SecretManagerService.SetIamPolicy:output_type -> google.iam.v1.Policy
	26, // 38: google.cloud.secretmanager.v1.SecretManagerService.GetIamPolicy:output_type -> google.iam.v1.Policy
	27, // 39: google.cloud.secretmanager.v1.SecretManagerService.TestIamPermissions:output_type -> google.iam.v1.TestIamPermissionsResponse
	20, // 40: google.cloud.secretmanager.v1.SecretManagerService.EnableManagedRotation:output_type -> google.cloud.secretmanager.v1.SecretVersion
	20, // 41: google.cloud.secretmanager.v1.SecretManagerService.RotateSecret:output_type -> google.cloud.secretmanager.v1.SecretVersion
	25, // [25:42] is the sub-list for method output_type
	8,  // [8:25] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_google_cloud_secretmanager_v1_service_proto_init() }
func file_google_cloud_secretmanager_v1_service_proto_init() {
	if File_google_cloud_secretmanager_v1_service_proto != nil {
		return
	}
	file_google_cloud_secretmanager_v1_resources_proto_init()
	file_google_cloud_secretmanager_v1_service_proto_msgTypes[4].OneofWrappers = []any{
		(*EnableManagedRotationRequest_CloudSqlSingleUserCredentials)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_cloud_secretmanager_v1_service_proto_rawDesc), len(file_google_cloud_secretmanager_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_google_cloud_secretmanager_v1_service_proto_goTypes,
		DependencyIndexes: file_google_cloud_secretmanager_v1_service_proto_depIdxs,
		MessageInfos:      file_google_cloud_secretmanager_v1_service_proto_msgTypes,
	}.Build()
	File_google_cloud_secretmanager_v1_service_proto = out.File
	file_google_cloud_secretmanager_v1_service_proto_goTypes = nil
	file_google_cloud_secretmanager_v1_service_proto_depIdxs = nil
}
