// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: google/cloud/osconfig/v1alpha/osconfig_zonal_service.proto

package osconfigpb

import (
	reflect "reflect"
	unsafe "unsafe"

	longrunningpb "cloud.google.com/go/longrunning/autogen/longrunningpb"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_google_cloud_osconfig_v1alpha_osconfig_zonal_service_proto protoreflect.FileDescriptor

const file_google_cloud_osconfig_v1alpha_osconfig_zonal_service_proto_rawDesc = "" +
	"\n" +
	":google/cloud/osconfig/v1alpha/osconfig_zonal_service.proto\x12\x1dgoogle.cloud.osconfig.v1alpha\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x19google/api/resource.proto\x1aCgoogle/cloud/osconfig/v1alpha/instance_os_policies_compliance.proto\x1a-google/cloud/osconfig/v1alpha/inventory.proto\x1a@google/cloud/osconfig/v1alpha/os_policy_assignment_reports.proto\x1a9google/cloud/osconfig/v1alpha/os_policy_assignments.proto\x1a1google/cloud/osconfig/v1alpha/vulnerability.proto\x1a#google/longrunning/operations.proto2\xe8\x1c\n" +
	"\x14OsConfigZonalService\x12\xc8\x02\n" +
	"\x18CreateOSPolicyAssignment\x12>.google.cloud.osconfig.v1alpha.CreateOSPolicyAssignmentRequest\x1a\x1d.google.longrunning.Operation\"\xcc\x01\xcaA9\n" +
	"\x12OSPolicyAssignment\x12#OSPolicyAssignmentOperationMetadata\xdaA3parent,os_policy_assignment,os_policy_assignment_id\x82\xd3\xe4\x93\x02T:\x14os_policy_assignment\"</v1alpha/{parent=projects/*/locations/*}/osPolicyAssignments\x12\xca\x02\n" +
	"\x18UpdateOSPolicyAssignment\x12>.google.cloud.osconfig.v1alpha.UpdateOSPolicyAssignmentRequest\x1a\x1d.google.longrunning.Operation\"\xce\x01\xcaA9\n" +
	"\x12OSPolicyAssignment\x12#OSPolicyAssignmentOperationMetadata\xdaA os_policy_assignment,update_mask\x82\xd3\xe4\x93\x02i:\x14os_policy_assignment2Q/v1alpha/{os_policy_assignment.name=projects/*/locations/*/osPolicyAssignments/*}\x12\xd4\x01\n" +
	"\x15GetOSPolicyAssignment\x12;.google.cloud.osconfig.v1alpha.GetOSPolicyAssignmentRequest\x1a1.google.cloud.osconfig.v1alpha.OSPolicyAssignment\"K\xdaA\x04name\x82\xd3\xe4\x93\x02>\x12</v1alpha/{name=projects/*/locations/*/osPolicyAssignments/*}\x12\xe7\x01\n" +
	"\x17ListOSPolicyAssignments\x12=.google.cloud.osconfig.v1alpha.ListOSPolicyAssignmentsRequest\x1a>.google.cloud.osconfig.v1alpha.ListOSPolicyAssignmentsResponse\"M\xdaA\x06parent\x82\xd3\xe4\x93\x02>\x12</v1alpha/{parent=projects/*/locations/*}/osPolicyAssignments\x12\x8b\x02\n" +
	"\x1fListOSPolicyAssignmentRevisions\x12E.google.cloud.osconfig.v1alpha.ListOSPolicyAssignmentRevisionsRequest\x1aF.google.cloud.osconfig.v1alpha.ListOSPolicyAssignmentRevisionsResponse\"Y\xdaA\x04name\x82\xd3\xe4\x93\x02L\x12J/v1alpha/{name=projects/*/locations/*/osPolicyAssignments/*}:listRevisions\x12\x86\x02\n" +
	"\x18DeleteOSPolicyAssignment\x12>.google.cloud.osconfig.v1alpha.DeleteOSPolicyAssignmentRequest\x1a\x1d.google.longrunning.Operation\"\x8a\x01\xcaA<\n" +
	"\x15google.protobuf.Empty\x12#OSPolicyAssignmentOperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02>*</v1alpha/{name=projects/*/locations/*/osPolicyAssignments/*}\x12\xff\x01\n" +
	"\x1fGetInstanceOSPoliciesCompliance\x12E.google.cloud.osconfig.v1alpha.GetInstanceOSPoliciesComplianceRequest\x1a;.google.cloud.osconfig.v1alpha.InstanceOSPoliciesCompliance\"X\xdaA\x04name\x82\xd3\xe4\x93\x02H\x12F/v1alpha/{name=projects/*/locations/*/instanceOSPoliciesCompliances/*}\x88\x02\x01\x12\x92\x02\n" +
	"!ListInstanceOSPoliciesCompliances\x12G.google.cloud.osconfig.v1alpha.ListInstanceOSPoliciesCompliancesRequest\x1aH.google.cloud.osconfig.v1alpha.ListInstanceOSPoliciesCompliancesResponse\"Z\xdaA\x06parent\x82\xd3\xe4\x93\x02H\x12F/v1alpha/{parent=projects/*/locations/*}/instanceOSPoliciesCompliances\x88\x02\x01\x12\xf9\x01\n" +
	"\x1bGetOSPolicyAssignmentReport\x12A.google.cloud.osconfig.v1alpha.GetOSPolicyAssignmentReportRequest\x1a7.google.cloud.osconfig.v1alpha.OSPolicyAssignmentReport\"^\xdaA\x04name\x82\xd3\xe4\x93\x02Q\x12O/v1alpha/{name=projects/*/locations/*/instances/*/osPolicyAssignments/*/report}\x12\x8f\x02\n" +
	"\x1dListOSPolicyAssignmentReports\x12C.google.cloud.osconfig.v1alpha.ListOSPolicyAssignmentReportsRequest\x1aD.google.cloud.osconfig.v1alpha.ListOSPolicyAssignmentReportsResponse\"c\xdaA\x06parent\x82\xd3\xe4\x93\x02T\x12R/v1alpha/{parent=projects/*/locations/*/instances/*/osPolicyAssignments/*}/reports\x12\xb9\x01\n" +
	"\fGetInventory\x122.google.cloud.osconfig.v1alpha.GetInventoryRequest\x1a(.google.cloud.osconfig.v1alpha.Inventory\"K\xdaA\x04name\x82\xd3\xe4\x93\x02>\x12</v1alpha/{name=projects/*/locations/*/instances/*/inventory}\x12\xd3\x01\n" +
	"\x0fListInventories\x125.google.cloud.osconfig.v1alpha.ListInventoriesRequest\x1a6.google.cloud.osconfig.v1alpha.ListInventoriesResponse\"Q\xdaA\x06parent\x82\xd3\xe4\x93\x02B\x12@/v1alpha/{parent=projects/*/locations/*/instances/*}/inventories\x12\xe1\x01\n" +
	"\x16GetVulnerabilityReport\x12<.google.cloud.osconfig.v1alpha.GetVulnerabilityReportRequest\x1a2.google.cloud.osconfig.v1alpha.VulnerabilityReport\"U\xdaA\x04name\x82\xd3\xe4\x93\x02H\x12F/v1alpha/{name=projects/*/locations/*/instances/*/vulnerabilityReport}\x12\xf7\x01\n" +
	"\x18ListVulnerabilityReports\x12>.google.cloud.osconfig.v1alpha.ListVulnerabilityReportsRequest\x1a?.google.cloud.osconfig.v1alpha.ListVulnerabilityReportsResponse\"Z\xdaA\x06parent\x82\xd3\xe4\x93\x02K\x12I/v1alpha/{parent=projects/*/locations/*/instances/*}/vulnerabilityReports\x1aK\xcaA\x17osconfig.googleapis.com\xd2A.https://www.googleapis.com/auth/cloud-platformB\xc4\x02\xeaA_\n" +
	"\x1fcompute.googleapis.com/Instance\x12<projects/{project}/locations/{location}/instances/{instance}\n" +
	"!com.google.cloud.osconfig.v1alphaB\x19OsConfigZonalServiceProtoP\x01Z=cloud.google.com/go/osconfig/apiv1alpha/osconfigpb;osconfigpb\xaa\x02\x1dGoogle.Cloud.OsConfig.V1Alpha\xca\x02\x1dGoogle\\Cloud\\OsConfig\\V1alpha\xea\x02 Google::Cloud::OsConfig::V1alphab\x06proto3"

var file_google_cloud_osconfig_v1alpha_osconfig_zonal_service_proto_goTypes = []any{
	(*CreateOSPolicyAssignmentRequest)(nil),           // 0: google.cloud.osconfig.v1alpha.CreateOSPolicyAssignmentRequest
	(*UpdateOSPolicyAssignmentRequest)(nil),           // 1: google.cloud.osconfig.v1alpha.UpdateOSPolicyAssignmentRequest
	(*GetOSPolicyAssignmentRequest)(nil),              // 2: google.cloud.osconfig.v1alpha.GetOSPolicyAssignmentRequest
	(*ListOSPolicyAssignmentsRequest)(nil),            // 3: google.cloud.osconfig.v1alpha.ListOSPolicyAssignmentsRequest
	(*ListOSPolicyAssignmentRevisionsRequest)(nil),    // 4: google.cloud.osconfig.v1alpha.ListOSPolicyAssignmentRevisionsRequest
	(*DeleteOSPolicyAssignmentRequest)(nil),           // 5: google.cloud.osconfig.v1alpha.DeleteOSPolicyAssignmentRequest
	(*GetInstanceOSPoliciesComplianceRequest)(nil),    // 6: google.cloud.osconfig.v1alpha.GetInstanceOSPoliciesComplianceRequest
	(*ListInstanceOSPoliciesCompliancesRequest)(nil),  // 7: google.cloud.osconfig.v1alpha.ListInstanceOSPoliciesCompliancesRequest
	(*GetOSPolicyAssignmentReportRequest)(nil),        // 8: google.cloud.osconfig.v1alpha.GetOSPolicyAssignmentReportRequest
	(*ListOSPolicyAssignmentReportsRequest)(nil),      // 9: google.cloud.osconfig.v1alpha.ListOSPolicyAssignmentReportsRequest
	(*GetInventoryRequest)(nil),                       // 10: google.cloud.osconfig.v1alpha.GetInventoryRequest
	(*ListInventoriesRequest)(nil),                    // 11: google.cloud.osconfig.v1alpha.ListInventoriesRequest
	(*GetVulnerabilityReportRequest)(nil),             // 12: google.cloud.osconfig.v1alpha.GetVulnerabilityReportRequest
	(*ListVulnerabilityReportsRequest)(nil),           // 13: google.cloud.osconfig.v1alpha.ListVulnerabilityReportsRequest
	(*longrunningpb.Operation)(nil),                   // 14: google.longrunning.Operation
	(*OSPolicyAssignment)(nil),                        // 15: google.cloud.osconfig.v1alpha.OSPolicyAssignment
	(*ListOSPolicyAssignmentsResponse)(nil),           // 16: google.cloud.osconfig.v1alpha.ListOSPolicyAssignmentsResponse
	(*ListOSPolicyAssignmentRevisionsResponse)(nil),   // 17: google.cloud.osconfig.v1alpha.ListOSPolicyAssignmentRevisionsResponse
	(*InstanceOSPoliciesCompliance)(nil),              // 18: google.cloud.osconfig.v1alpha.InstanceOSPoliciesCompliance
	(*ListInstanceOSPoliciesCompliancesResponse)(nil), // 19: google.cloud.osconfig.v1alpha.ListInstanceOSPoliciesCompliancesResponse
	(*OSPolicyAssignmentReport)(nil),                  // 20: google.cloud.osconfig.v1alpha.OSPolicyAssignmentReport
	(*ListOSPolicyAssignmentReportsResponse)(nil),     // 21: google.cloud.osconfig.v1alpha.ListOSPolicyAssignmentReportsResponse
	(*Inventory)(nil),                                 // 22: google.cloud.osconfig.v1alpha.Inventory
	(*ListInventoriesResponse)(nil),                   // 23: google.cloud.osconfig.v1alpha.ListInventoriesResponse
	(*VulnerabilityReport)(nil),                       // 24: google.cloud.osconfig.v1alpha.VulnerabilityReport
	(*ListVulnerabilityReportsResponse)(nil),          // 25: google.cloud.osconfig.v1alpha.ListVulnerabilityReportsResponse
}
var file_google_cloud_osconfig_v1alpha_osconfig_zonal_service_proto_depIdxs = []int32{
	0,  // 0: google.cloud.osconfig.v1alpha.OsConfigZonalService.CreateOSPolicyAssignment:input_type -> google.cloud.osconfig.v1alpha.CreateOSPolicyAssignmentRequest
	1,  // 1: google.cloud.osconfig.v1alpha.OsConfigZonalService.UpdateOSPolicyAssignment:input_type -> google.cloud.osconfig.v1alpha.UpdateOSPolicyAssignmentRequest
	2,  // 2: google.cloud.osconfig.v1alpha.OsConfigZonalService.GetOSPolicyAssignment:input_type -> google.cloud.osconfig.v1alpha.GetOSPolicyAssignmentRequest
	3,  // 3: google.cloud.osconfig.v1alpha.OsConfigZonalService.ListOSPolicyAssignments:input_type -> google.cloud.osconfig.v1alpha.ListOSPolicyAssignmentsRequest
	4,  // 4: google.cloud.osconfig.v1alpha.OsConfigZonalService.ListOSPolicyAssignmentRevisions:input_type -> google.cloud.osconfig.v1alpha.ListOSPolicyAssignmentRevisionsRequest
	5,  // 5: google.cloud.osconfig.v1alpha.OsConfigZonalService.DeleteOSPolicyAssignment:input_type -> google.cloud.osconfig.v1alpha.DeleteOSPolicyAssignmentRequest
	6,  // 6: google.cloud.osconfig.v1alpha.OsConfigZonalService.GetInstanceOSPoliciesCompliance:input_type -> google.cloud.osconfig.v1alpha.GetInstanceOSPoliciesComplianceRequest
	7,  // 7: google.cloud.osconfig.v1alpha.OsConfigZonalService.ListInstanceOSPoliciesCompliances:input_type -> google.cloud.osconfig.v1alpha.ListInstanceOSPoliciesCompliancesRequest
	8,  // 8: google.cloud.osconfig.v1alpha.OsConfigZonalService.GetOSPolicyAssignmentReport:input_type -> google.cloud.osconfig.v1alpha.GetOSPolicyAssignmentReportRequest
	9,  // 9: google.cloud.osconfig.v1alpha.OsConfigZonalService.ListOSPolicyAssignmentReports:input_type -> google.cloud.osconfig.v1alpha.ListOSPolicyAssignmentReportsRequest
	10, // 10: google.cloud.osconfig.v1alpha.OsConfigZonalService.GetInventory:input_type -> google.cloud.osconfig.v1alpha.GetInventoryRequest
	11, // 11: google.cloud.osconfig.v1alpha.OsConfigZonalService.ListInventories:input_type -> google.cloud.osconfig.v1alpha.ListInventoriesRequest
	12, // 12: google.cloud.osconfig.v1alpha.OsConfigZonalService.GetVulnerabilityReport:input_type -> google.cloud.osconfig.v1alpha.GetVulnerabilityReportRequest
	13, // 13: google.cloud.osconfig.v1alpha.OsConfigZonalService.ListVulnerabilityReports:input_type -> google.cloud.osconfig.v1alpha.ListVulnerabilityReportsRequest
	14, // 14: google.cloud.osconfig.v1alpha.OsConfigZonalService.CreateOSPolicyAssignment:output_type -> google.longrunning.Operation
	14, // 15: google.cloud.osconfig.v1alpha.OsConfigZonalService.UpdateOSPolicyAssignment:output_type -> google.longrunning.Operation
	15, // 16: google.cloud.osconfig.v1alpha.OsConfigZonalService.GetOSPolicyAssignment:output_type -> google.cloud.osconfig.v1alpha.OSPolicyAssignment
	16, // 17: google.cloud.osconfig.v1alpha.OsConfigZonalService.ListOSPolicyAssignments:output_type -> google.cloud.osconfig.v1alpha.ListOSPolicyAssignmentsResponse
	17, // 18: google.cloud.osconfig.v1alpha.OsConfigZonalService.ListOSPolicyAssignmentRevisions:output_type -> google.cloud.osconfig.v1alpha.ListOSPolicyAssignmentRevisionsResponse
	14, // 19: google.cloud.osconfig.v1alpha.OsConfigZonalService.DeleteOSPolicyAssignment:output_type -> google.longrunning.Operation
	18, // 20: google.cloud.osconfig.v1alpha.OsConfigZonalService.GetInstanceOSPoliciesCompliance:output_type -> google.cloud.osconfig.v1alpha.InstanceOSPoliciesCompliance
	19, // 21: google.cloud.osconfig.v1alpha.OsConfigZonalService.ListInstanceOSPoliciesCompliances:output_type -> google.cloud.osconfig.v1alpha.ListInstanceOSPoliciesCompliancesResponse
	20, // 22: google.cloud.osconfig.v1alpha.OsConfigZonalService.GetOSPolicyAssignmentReport:output_type -> google.cloud.osconfig.v1alpha.OSPolicyAssignmentReport
	21, // 23: google.cloud.osconfig.v1alpha.OsConfigZonalService.ListOSPolicyAssignmentReports:output_type -> google.cloud.osconfig.v1alpha.ListOSPolicyAssignmentReportsResponse
	22, // 24: google.cloud.osconfig.v1alpha.OsConfigZonalService.GetInventory:output_type -> google.cloud.osconfig.v1alpha.Inventory
	23, // 25: google.cloud.osconfig.v1alpha.OsConfigZonalService.ListInventories:output_type -> google.cloud.osconfig.v1alpha.ListInventoriesResponse
	24, // 26: google.cloud.osconfig.v1alpha.OsConfigZonalService.GetVulnerabilityReport:output_type -> google.cloud.osconfig.v1alpha.VulnerabilityReport
	25, // 27: google.cloud.osconfig.v1alpha.OsConfigZonalService.ListVulnerabilityReports:output_type -> google.cloud.osconfig.v1alpha.ListVulnerabilityReportsResponse
	14, // [14:28] is the sub-list for method output_type
	0,  // [0:14] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_google_cloud_osconfig_v1alpha_osconfig_zonal_service_proto_init() }
func file_google_cloud_osconfig_v1alpha_osconfig_zonal_service_proto_init() {
	if File_google_cloud_osconfig_v1alpha_osconfig_zonal_service_proto != nil {
		return
	}
	file_google_cloud_osconfig_v1alpha_instance_os_policies_compliance_proto_init()
	file_google_cloud_osconfig_v1alpha_inventory_proto_init()
	file_google_cloud_osconfig_v1alpha_os_policy_assignment_reports_proto_init()
	file_google_cloud_osconfig_v1alpha_os_policy_assignments_proto_init()
	file_google_cloud_osconfig_v1alpha_vulnerability_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_cloud_osconfig_v1alpha_osconfig_zonal_service_proto_rawDesc), len(file_google_cloud_osconfig_v1alpha_osconfig_zonal_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_google_cloud_osconfig_v1alpha_osconfig_zonal_service_proto_goTypes,
		DependencyIndexes: file_google_cloud_osconfig_v1alpha_osconfig_zonal_service_proto_depIdxs,
	}.Build()
	File_google_cloud_osconfig_v1alpha_osconfig_zonal_service_proto = out.File
	file_google_cloud_osconfig_v1alpha_osconfig_zonal_service_proto_goTypes = nil
	file_google_cloud_osconfig_v1alpha_osconfig_zonal_service_proto_depIdxs = nil
}
