---
name: config check
on:
  pull_request:
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
  config-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      # Use this action, rather than a file filter so that we can make this
      # mandatory.
      # See https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#example-including-branches
      # for more details.
      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            librarian:
              - 'librarian.yaml'
              - '.librarian/**'
      - name: Config check
        if: steps.filter.outputs.librarian == 'true'
        run: |
          V="$(sed -n 's/^version: *//p' librarian.yaml)"
          go run "github.com/googleapis/librarian/tool/cmd/configcheck@${V}" .
      - name: Update library versions and regenerate
        if: failure()
        run: |
          echo "Library configuration is different between state.yaml and librarian.yaml.
          Update library configuration in the configs according to the error message and
          regenerate libraries using:
          
          V=\$(sed -n 's/^version: *//p' librarian.yaml)
          go run github.com/googleapis/librarian/cmd/librarian@\${V} generate --all
          "
