---
name: config check
on:
  pull_request:
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
  config-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Config check
        run: |
          V=$(sed -n 's/^version: *//p' librarian.yaml)
          go run github.com/googleapis/librarian/tool/cmd/configcheck@${V} .
      - name: Update library versions and regenerate
        if: failure()
        run: |
          echo "Library version is different between state.yaml and librarian.yaml.
          Update versions in the configs according to the error message and
          regenerate libraries using:
          
          V=\$(sed -n 's/^version: *//p' librarian.yaml)
          go run github.com/googleapis/librarian/cmd/librarian@\${V} generate --all
          "
