---
name: config check
on:
  pull_request:
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
  config-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Config check
      run: |
        V=$(sed -n 's/^version: *//p' librarian.yaml)
        go run github.com/googleapis/librarian/tool/cmd/configcheck@${V} .
