---
name: generation-check
on:
  schedule:
    # Runs every day at 4:00 AM UTC
    - cron: '0 4 * * *'
  # Allows manual triggering for debugging purpose.
  workflow_dispatch:
permissions:
  contents: read
jobs:
  regeneration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: '1.26.x'
      - name: Install tools
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.36.11 && \
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.3.0 && \
          go install github.com/googleapis/gapic-generator-go/cmd/protoc-gen-go_gapic@v0.57.0 && \
          go install golang.org/x/tools/cmd/goimports@latest
      - name: Regeneration
        run: ./.github/workflows/regenerate.sh