---
name: generation-check
on:
  push:
    branches:
      - main
  pull_request:
  # Allows manual triggering for debugging purpose.
  workflow_dispatch:
permissions:
  contents: read
  issues: write
jobs:
  regeneration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          persist-credentials: false
      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4
        id: changes
        with:
          filters: |
            librarian:
              - 'librarian.yaml'
      # Version of librarian is pulled from librarian.yaml,
      # main corresponds to the action's source definition.
      - uses: googleapis/librarian@main # zizmor: ignore[unpinned-uses]
        if: steps.changes.outputs.librarian == 'true' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
        with:
          protoc-version: '33.2'
          protoc-checksum: '8c0a8577311720cc83488f813aeb5046d69cb9824cbf39cb7447e0c5132d677952d5bb7c1130d9df381835eee7352828878d409873ebb407d7a4649ea2a4aee5'
      - name: Install tools
        if: steps.changes.outputs.librarian == 'true' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
        run: librarian install -v
      - name: Regenerate
        if: steps.changes.outputs.librarian == 'true' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
        run: |
          librarian generate --all -v
          if [ -n "$(git status --porcelain)" ]; then
            git status
            echo "==================== GIT DIFF ===================="
            git diff
            echo "=================================================="
            echo "Regeneration failed. Please run 'librarian generate --all' to update the generated files."
            exit 1
          fi
      - name: Create issue if previous step fails
        if: ${{ failure() && github.ref == 'refs/heads/main' }}
        uses: googleapis/librarian/.github/actions/create-issue-on-failure@main # zizmor: ignore[unpinned-uses]
        with:
          title: "Librarian generate diff check failed on main branch"
          body: |
            The librarian generate diff check failed on main branch.

            To keep the `main` branch healthy, please consider **reverting the triggering change** first. Once the revert is merged, you can investigate the failure and submit a new PR with the fix.

            Please check the logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
