---
name: librariangen
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read  #  to fetch code (actions/checkout)

env:
  GOTOOLCHAIN: local

jobs:
  vet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.24.x'
    - name: Install tools
      run: |
        go install golang.org/x/lint/golint@latest && \
        go install golang.org/x/tools/cmd/goimports@latest && \
        go install honnef.co/go/tools/cmd/staticcheck@latest
    - name: Run tests
      run: |
        cd internal/librariangen
        go test ./...
